/**
 * Fetches complete Proverbs 1-30 for ZH/KJV/KO/JA from bolls.life / bible-api.com
 * Run: node scripts/fetch_proverbs.mjs
 */
import fs from 'fs';
import https from 'https';

function get(url) {
  return new Promise((resolve, reject) => {
    https.get(url, {
      headers: { 'User-Agent': 'Mozilla/5.0', 'Accept': '*/*' }
    }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location)
        return get(res.headers.location).then(resolve).catch(reject);
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    }).on('error', reject);
  });
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

// Strip bolls.life HTML (has <i>, <sup> for ruby/furigana etc)
function stripHtml(s) {
  return (s || '')
    .replace(/<sup[^>]*>[\s\S]*?<\/sup>/gi, '') // remove ruby annotations
    .replace(/<[^>]+>/g, '')
    .replace(/,\s*[ぁ-ん]+/g, '')  // remove hiragana readings like ",こ"
    .replace(/\s+/g, ' ')
    .trim();
}

// bolls.life: book 20 = Proverbs
async function fetchBolls(version, chapter) {
  const url = `https://bolls.life/get-text/${version}/20/${chapter}/`;
  const raw = await get(url);
  const verses = JSON.parse(raw);
  if (!Array.isArray(verses) || verses.length === 0) return null;
  return verses.map(v => stripHtml(v.text)).join(' ');
}

// bible-api.com (best for KJV — clean text)
async function fetchKJV(chapter) {
  const url = `https://bible-api.com/proverbs%20${chapter}?translation=kjv`;
  const raw = await get(url);
  const data = JSON.parse(raw);
  if (!data.verses) throw new Error('No verses');
  return data.verses.map(v => v.text.replace(/\n/g, ' ').trim()).join(' ');
}

const NUM_CHAPTERS = 30;

async function fetchLang(label, fetchFn) {
  console.log(`\n── ${label} ──`);
  const chapters = [];
  for (let ch = 1; ch <= NUM_CHAPTERS; ch++) {
    process.stdout.write(`  ch${ch}... `);
    await sleep(350);
    try {
      const text = await fetchFn(ch);
      chapters.push(text || '');
      process.stdout.write(text ? `✓ (${text.split(/\s+/).length}w)\n` : '✗ empty\n');
    } catch(e) {
      process.stdout.write(`✗ ${e.message.slice(0,50)}\n`);
      chapters.push('');
    }
  }
  return chapters;
}

function esc(t) {
  return (t || '').replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function makeSet(exportName, id, title, desc, langProp, chapterTexts, refFn, titleFn) {
  let s = `export const ${exportName} = [\n  {\n    id: "${id}",\n    title: "${title}",\n    description: "${desc}",\n`;
  if (langProp) s += `    language: "${langProp}",\n`;
  s += `    verses: [\n`;
  chapterTexts.forEach((t, i) => {
    const ch = i + 1;
    s += `      { id: "prv-${id.replace('proverbs-','')}-${ch}", reference: "${refFn(ch)}", title: "${titleFn(ch)}", text: \`${esc(t)}\` }`;
    s += i < 29 ? ',\n' : '\n';
  });
  s += `    ]\n  }\n];\n`;
  return s;
}

async function main() {
  console.log('=== Fetching complete Proverbs 1-30 in 4 languages ===');

  const kjv = await fetchLang('KJV (bible-api.com)', fetchKJV);
  const zh  = await fetchLang('CUV Traditional Chinese (bolls.life)', ch => fetchBolls('CUV', ch));
  const ko  = await fetchLang('KRV Korean (bolls.life)', ch => fetchBolls('KRV', ch));
  const ja  = await fetchLang('JPKJV Japanese (bolls.life)', ch => fetchBolls('JPKJV', ch));

  let out = `// Auto-generated by scripts/fetch_proverbs.mjs — DO NOT EDIT MANUALLY
// Complete Proverbs chapters 1-30 in Chinese (CUV), English (KJV), Korean (KRV), Japanese (JPKJV)
// Each entry = one full chapter, intended for Rain Mode one-chapter-per-game\n\n`;

  out += makeSet('VERSE_SETS_PROVERBS_ZH', 'proverbs-zh',
    '箴言 1–30（和合本）',
    '箴言一至三十章，每章一局，雨滴模式逐章背誦挑戰。',
    null, zh,
    ch => `箴言 ${ch}`, ch => `箴言第${ch}章`);
  out += '\n';

  out += makeSet('VERSE_SETS_PROVERBS_KJV', 'proverbs-kjv',
    'Proverbs 1–30 (KJV)',
    'Complete Proverbs chapters 1–30, one chapter per round for Rain Mode.',
    null, kjv,
    ch => `Proverbs ${ch}`, ch => `Proverbs Chapter ${ch}`);
  out += '\n';

  out += makeSet('VERSE_SETS_PROVERBS_KO', 'proverbs-ko',
    '잠언 1–30',
    '잠언 1장부터 30장까지, 한 챕터씩 말씀비(Rain Mode) 암송 도전.',
    'ko', ko,
    ch => `잠언 ${ch}`, ch => `잠언 ${ch}장`);
  out += '\n';

  out += makeSet('VERSE_SETS_PROVERBS_JA', 'proverbs-ja',
    '箴言 1–30（日本語）',
    '箴言1章から30章まで、1章ずつ御言葉の雨モードで暗唱にチャレンジ。',
    'ja', ja,
    ch => `箴言 ${ch}`, ch => `箴言第${ch}章`);

  const outPath = new URL('../src/verses_proverbs.js', import.meta.url).pathname;
  fs.writeFileSync(outPath, out, 'utf8');
  console.log(`\n✅ Written: ${outPath} (${(out.length/1024).toFixed(0)} KB)`);

  for (const [label, arr] of [['ZH', zh], ['KJV', kjv], ['KO', ko], ['JA', ja]]) {
    const missing = arr.map((t,i) => (!t || t.length < 40) ? i+1 : null).filter(Boolean);
    if (missing.length) console.warn(`⚠️  ${label} missing: ch ${missing.join(', ')}`);
    else console.log(`✓ ${label}: all 30 chapters present`);
  }

  console.log('\n── Samples ──');
  if (kjv[0]) console.log('KJV ch1:', kjv[0].substring(0, 140) + '...');
  if (zh[0])  console.log('ZH  ch1:', zh[0].substring(0, 140) + '...');
  if (ko[0])  console.log('KO  ch1:', ko[0].substring(0, 140) + '...');
  if (ja[0])  console.log('JA  ch1:', ja[0].substring(0, 140) + '...');
}

main().catch(e => { console.error('FATAL:', e); process.exit(1); });
