import json

es = {
    "我的園子": "Mi Jardín",
    "🌳 我的園子": "🌳 Mi Jardín",
    "多人連線": "Multijugador",
    "🎮 多人連線": "🎮 Multijugador",
    "排行榜": "Clasificación",
    "🏆 排行榜": "🏆 Clasificación",
    "搜尋": "Buscar",
    "🔍 搜尋": "🔍 Buscar",
    "地圖": "Mapa",
    "🗺️ 地圖": "🗺️ Mapa",
    "返回目錄": "Volver",
    "目前選擇": "Selección actual",
    "九宮格": "9-Cuadrículas",
    "四宮格": "4-Cuadrículas",
    "經文雨": "Lluvia de Versículos",
    "單字干擾": "Interferencia de Palabras",
    "無干擾": "Sin Interferencia",
    "難度 0": "Dificultad 0",
    "難度 1": "Dificultad 1",
    "難度 2": "Dificultad 2",
    "難度 3": "Dificultad 3",
    "挑戰": "Jugar",
    "播放全部": "Reproducir todo",
    "邀人PK": "Invitar",
    "經文出處(點擊觀看)": "Referencia (Click)",
    "排行": "Rango",
    "設定": "Ajustes",
    "選擇比賽經文組": "Seleccionar Conjunto",
    "沒有找到匹配的經文組。": "No se encontraron conjuntos coincidentes.",
    "準備！": "¡Listo!",
    "已準備": "Listo",
    "開始": "Empezar",
    "加入對戰": "Unirse a partida",
    "建立對戰": "Crear partida",
    "你的名字:": "Tu nombre:",
    "登入 / 修改": "Iniciar / Modificar",
    "登出": "Cerrar sesión",
    "經文組": "Conjunto de Versículos",
    "隨機挑戰所選題數": "Desafío aleatorio",
    "自動播放全部經文圖卡與語音": "Reproducción automática con audio",
    "邀請朋友一起玩": "Invitar amigos",
    "分享挑戰連結": "Compartir enlace",
    "經典挑戰": "Desafío clásico",
    "立刻挑戰": "Desafiar ahora",
    "最受歡迎": "Más populares",
    "最新": "Más recientes",
    "作者": "Autor",
    "點閱次數": "Vistas",
    "Verserain 官方": "Oficial de Verserain",
    "匿名玩家": "Jugador anónimo",
    "QR 碼": "Código QR"
}

tr = {
    "我的園子": "Bahçem",
    "🌳 我的園子": "🌳 Bahçem",
    "多人連線": "Çok Oyunculu",
    "🎮 多人連線": "🎮 Çok Oyunculu",
    "排行榜": "Liderlik Tablosu",
    "🏆 排行榜": "🏆 Liderlik Tablosu",
    "搜尋": "Arama",
    "🔍 搜尋": "🔍 Arama",
    "地圖": "Harita",
    "🗺️ 地圖": "🗺️ Harita",
    "返回目錄": "Geri Dön",
    "目前選擇": "Mevcut Seçim",
    "九宮格": "9'lu Izgara",
    "四宮格": "4'lü Izgara",
    "經文雨": "Ayet Yağmuru",
    "單字干擾": "Kelime Karışıklığı",
    "無干擾": "Karışıklık Yok",
    "難度 0": "Zorluk 0",
    "難度 1": "Zorluk 1",
    "難度 2": "Zorluk 2",
    "難度 3": "Zorluk 3",
    "挑戰": "Oyna",
    "播放全部": "Hepsini Oynat",
    "邀人PK": "Davet Et",
    "經文出處(點擊觀看)": "Referans (Tıkla)",
    "排行": "Sıra",
    "設定": "Ayarlar",
    "選擇比賽經文組": "Ayet Seti Seç",
    "沒有找到匹配的經文組。": "Eşleşen set bulunamadı.",
    "準備！": "Hazır!",
    "已準備": "Hazır",
    "開始": "Başla",
    "加入對戰": "Maça Katıl",
    "建立對戰": "Maç Oluştur",
    "你的名字:": "Adın:",
    "登入 / 修改": "Giriş / Değiştir",
    "登出": "Çıkış Yap",
    "經文組": "Ayet Seti",
    "隨機挑戰所選題數": "Rastgele Meydan Okuma",
    "自動播放全部經文圖卡與語音": "Sesli Otomatik Oynat",
    "邀請朋友一起玩": "Arkadaşlarını Davet Et",
    "分享挑戰連結": "Bağlantıyı Paylaş",
    "經典挑戰": "Klasik Meydan Okuma",
    "立刻挑戰": "Hemen Oyna",
    "最受歡迎": "En Popüler",
    "最新": "En Yeni",
    "作者": "Yazar",
    "點閱次數": "Görüntüleme",
    "Verserain 官方": "Verserain Resmi",
    "匿名玩家": "Anonim Oyuncu",
    "QR 碼": "QR Kod"
}

de = {
    "我的園子": "Mein Garten",
    "🌳 我的園子": "🌳 Mein Garten",
    "多人連線": "Mehrspieler",
    "🎮 多人連線": "🎮 Mehrspieler",
    "排行榜": "Bestenliste",
    "🏆 排行榜": "🏆 Bestenliste",
    "搜尋": "Suche",
    "🔍 搜尋": "🔍 Suche",
    "地圖": "Karte",
    "🗺️ 地圖": "🗺️ Karte",
    "返回目錄": "Zurück",
    "目前選擇": "Aktuelle Auswahl",
    "九宮格": "9-Gitter",
    "四宮格": "4-Gitter",
    "經文雨": "Versregen",
    "單字干擾": "Wortstörung",
    "無干擾": "Ohne Störung",
    "難度 0": "Schwierigkeit 0",
    "難度 1": "Schwierigkeit 1",
    "難度 2": "Schwierigkeit 2",
    "難度 3": "Schwierigkeit 3",
    "挑戰": "Spielen",
    "播放全部": "Alle abspielen",
    "邀人PK": "Einladen",
    "經文出處(點擊觀看)": "Referenz (Klick)",
    "排行": "Rang",
    "設定": "Einstellungen",
    "選擇比賽經文組": "Set auswählen",
    "沒有找到匹配的經文組。": "Keine passenden Sets gefunden.",
    "準備！": "Bereit!",
    "已準備": "Bereit",
    "開始": "Start",
    "加入對戰": "Spiel beitreten",
    "建立對戰": "Spiel erstellen",
    "你的名字:": "Dein Name:",
    "登入 / 修改": "Anmelden / Ändern",
    "登出": "Abmelden",
    "經文組": "Vers-Set",
    "隨機挑戰所選題數": "Zufällige Herausforderung",
    "自動播放全部經文圖卡與語音": "Automatische Wiedergabe",
    "邀請朋友一起玩": "Freunde einladen",
    "分享挑戰連結": "Link teilen",
    "經典挑戰": "Klassische Herausforderung",
    "立刻挑戰": "Jetzt spielen",
    "最受歡迎": "Beliebteste",
    "最新": "Neueste",
    "作者": "Autor",
    "點閱次數": "Aufrufe",
    "Verserain 官方": "Verserain Offiziell",
    "匿名玩家": "Anonymer Spieler",
    "QR 碼": "QR-Code"
}

with open('esDict.json', 'w', encoding='utf-8') as f:
    json.dump(es, f, ensure_ascii=False, indent=2)
with open('trDict.json', 'w', encoding='utf-8') as f:
    json.dump(tr, f, ensure_ascii=False, indent=2)
with open('deDict.json', 'w', encoding='utf-8') as f:
    json.dump(de, f, ensure_ascii=False, indent=2)

print("Created dict files!")
