// The 'manual' page — moved out of App.jsx unchanged (UI/UX 第 4 階段).
import { CloudRain, Edit, Headphones, Languages, Map, Mic, Play, Trophy } from 'lucide-react';
import ManualSearch from '../ManualSearch.jsx';
import { ManualVideo } from '../ManualVideo.jsx';

export default function ManualPage({ t, manualBodyRef, scrollMenuTo, uiLang }) {
  return (
    <div style={{ padding: '2rem', maxWidth: '800px', margin: '0 auto', color: '#1e293b', lineHeight: '1.8' }}>
      <>
        <h1 style={{ color: '#3b82f6', marginBottom: '1.5rem', textAlign: 'center', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}><CloudRain size={32} /> {t("VerseRain 經文雨 操作手冊", "VerseRain User Manual")}</h1>
        <p style={{ textAlign: 'center', fontSize: '1.1rem', marginBottom: '3rem' }}>
          <span dangerouslySetInnerHTML={{ __html: t("歡迎進入 <strong>VerseRain 經文雨</strong>！這是一個結合聆聽、挑戰與學習的互動背經平台。<br />在這裡您可以挑戰全球經文組、建立個人專屬的經文組，也能用自己的聲音把經文分享給朋友！", "Welcome to <strong>VerseRain</strong>! An interactive Scripture-memory platform that combines listening, challenge and learning.<br />Here you can challenge global verse sets, build your own library, and share verses in your own voice with friends!") }} />
        </p>

        <ManualSearch t={t} bodyRef={manualBodyRef} lang={uiLang} onJump={(el) => el && scrollMenuTo(el)} />
        <div ref={manualBodyRef}>

        <h2 style={{ borderBottom: '2px solid #e2e8f0', paddingBottom: '0.5rem', marginTop: '2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Play size={22} /> {t("一、如何開始遊玩？", "1. How to Play?")}</h2>
        <p>{t("只需簡單三步，您就能進入背經的挑戰中！", "Just three simple steps to start your scripture memorization challenge!")}</p>

        <h3 style={{ marginTop: '1.5rem', color: '#0f172a' }}>{t("1. 點下方的「經文組」分頁", "1. Open the \"Sets\" tab at the bottom")}</h3>
        <p><span dangerouslySetInnerHTML={{ __html: t("點畫面下方的 <strong>「經文組」</strong> 分頁，就會看到系統與玩家建立的所有公開經文組，可依最新、標題或最受歡迎排序。", "Tap the <strong>\"Sets\"</strong> tab at the bottom of the screen to see every public verse set created by the system and by players. Sort by newest, title, or most popular.") }} /></p>
        <h3 style={{ marginTop: '1.5rem', color: '#0f172a' }}>{t("2. 選擇想要挑戰的經文組", "2. Select a Verse Set")}</h3>
        <p><span dangerouslySetInnerHTML={{ __html: t("點選列表中的標題（例如：<strong>約翰福音 核心經文</strong>），進入經文組頁面。每一節經文右側有「聆聽」和「挑戰」按鈕；上方的「全部聆聽」會從第一節連續播放。", "Tap a title in the list (e.g. <strong>Gospel of John Core Verses</strong>) to open the set page. Each verse has Listen and Challenge buttons; \"Listen to all\" at the top plays the set from the first verse.") }} /></p>
        <h3 style={{ marginTop: '1.5rem', color: '#0f172a' }}>{t("3. 開始挑戰", "3. Start the Challenge")}</h3>
        <p><span dangerouslySetInnerHTML={{ __html: t("點該節右側的綠色 <strong>⚡ 挑戰</strong> 鍵，選擇遊戲模式（九宮格／經文雨／語音模式）與難度，按「開始挑戰」——三秒後經文雨就傾盆而下！依正確順序點擊落下的方塊，越快完成、時間加成越高。", "Tap the green <strong>⚡ Challenge</strong> button next to a verse, choose the game mode (Square / Verse Rain / Voice Mode) and difficulty, then press \"Start Challenge\" — three seconds later the verse rain pours down! Tap the falling blocks in the right order; the faster you finish, the bigger the time bonus.") }} /></p>
        <ManualVideo src="/manual/start-game.mp4" poster="/manual/start-game.jpg" caption={t("教學影片：從大廳進入經文組 → 選經文組 → ⚡ 挑戰 → 選模式 → 依序點擊方塊，完成一次挑戰。", "Tutorial: lobby → Scripture Sets → pick a set → ⚡ Challenge → choose a mode → tap the blocks in order to finish a challenge.")} />

        <h2 style={{ borderBottom: '2px solid #e2e8f0', paddingBottom: '0.5rem', marginTop: '2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Edit size={24} /> {t("二、如何自建專屬「經文組」？", "2. How to Build Your Own \"Verse Set\"")}</h2>
        <p>{t("只要登入帳號，任何人都可以打造自己的主日學、小組或個人靈修專屬經文組，建好就能聆聽、挑戰、分享。", "Any signed-in user can build a verse set for Sunday school, a small group or personal devotion, then listen to it, challenge it and share it.")}</p>
        <ol style={{ paddingLeft: '1.5rem', marginBottom: '2rem' }}>
          <li><span dangerouslySetInnerHTML={{ __html: t("先<strong>登入</strong>，再點下方的 <strong>「經文組」</strong> 分頁，進入上方的 <strong>「我的經文組」</strong>。", "<strong>Sign in</strong>, open the <strong>\"Sets\"</strong> tab at the bottom, then go to <strong>\"My Custom Sets\"</strong> at the top.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("點 <strong>「＋ 建立新經文組」</strong>，填上標題與簡介；也可以挑一張背景圖片、選背景音樂或上傳自己的音樂。", "Tap <strong>\"+ Create New Set\"</strong>, give it a title and a description; you can also pick a background image and background music (or upload your own).") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("在經文列表選好書卷、輸入 <strong>章:節</strong>（如 <code>3:16</code> 或 <code>6:9-13</code>），按 <strong>Enter 或 Tab</strong>，系統就會自動抓取完整經文。", "In the verse list pick the book, type the <strong>chapter:verse</strong> (e.g. <code>3:16</code> or <code>6:9-13</code>) and press <strong>Enter or Tab</strong> — the full text is fetched for you.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("經文很多？用 <strong>「輸入出處批次匯入」</strong>，一次貼上多個出處（每行一個或用逗號分隔）。逗號後面的純節數會接在同一章：<code>約翰福音 1:1, 4</code> 就是 1:1 與 1:4。", "Many verses? Use <strong>\"Import by references\"</strong> and paste several references at once (one per line or comma-separated). A bare verse number after a comma stays in the same chapter: <code>John 1:1, 4</code> means 1:1 and 1:4.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("每一節旁邊都有 🎙️ 麥克風，可以順手錄下自己的親聲朗讀。", "Each verse row has a 🎙️ mic so you can record your own reading right there.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("確認無誤後點 <strong>「儲存經文組」</strong>。這份經文組就會出現在「經文組」，大家都可以聆聽與挑戰。", "When everything looks right, tap <strong>\"Save Set\"</strong>. The set appears in \"Scripture Sets\" for everyone to listen to and challenge.") }} /></li>
        </ol>
        <div style={{ backgroundColor: '#f0fdf4', borderLeft: '4px solid #22c55e', padding: '1rem', borderRadius: '4px', marginBottom: '3rem' }}>
          <span dangerouslySetInnerHTML={{ __html: t("<strong>提示：</strong>經文抓取串接了各語言的聖經資料庫（和合本、ESV、KJV…），能大幅省去打字與校稿的時間；建好的經文組還能用「翻譯」一鍵在地化到其他語言（見第七章）。", "<strong>Tip:</strong> Verse fetching is wired to Bible databases in every supported language (CUV, ESV, KJV…), which saves a lot of typing and proofreading; a finished set can also be localized to another language with one tap via \"Translate\" (see section 7).") }} />
        </div>

        <h2 style={{ borderBottom: '2px solid #e2e8f0', paddingBottom: '0.5rem', marginTop: '2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Mic size={22} /> {t("三、全新語音模式 (Voice Mode)", "3. New Voice Mode")}</h2>
        <p><span dangerouslySetInnerHTML={{ __html: t("除了點擊方塊，您現在可以直接<strong>用「唸」的來背經文！</strong>", "Besides clicking blocks, you can now recite verses directly <strong>using your voice!</strong>") }} /></p>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '2rem' }}>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>智慧模糊辨識：</strong> 系統內建強大的中文拼音模糊比對。就算有台灣國語、捲舌平舌音不分，只要發音相近就能過關！", "<strong>Smart Fuzzy Recognition:</strong> The system features powerful fuzzy pinyin matching. Even with accents or imprecise pronunciation, similar sounds will pass!") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>貼心提示系統：</strong> 如果卡詞了，系統會在 3 秒後自動給予局部提示，幫助您順利接下去。", "<strong>Helpful Hint System:</strong> If you get stuck, the system will automatically provide a partial hint after 3 seconds to help you continue.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>分數加成獎勵：</strong> 為了鼓勵大家開口宣告神的話語，在語音模式中，您的<strong>「剩餘時間加成」權重會大幅提升 50%</strong>！", "<strong>Score Bonus:</strong> To encourage proclaiming God's word out loud, your <strong>\"Remaining Time Bonus\" weight is increased by 50%</strong> in Voice Mode!") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>預備倒數：</strong>宣告經文出處後，畫面會出現「預備…3…2…1…開始！」的大字倒數，讓你清楚知道什麼時候輪到自己開口。", "<strong>Ready countdown:</strong> After the reference is announced, a big \"Ready… 3… 2… 1… Go!\" countdown shows on screen so you know exactly when it's your turn to speak.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>挑戰前先設定：</strong>按下「挑戰」會先跳出設定視窗，讓你選擇遊戲模式（九宮格／經文雨／語音模式）與難度。語音模式可勾選「不要複誦我背過的經文」，節奏更順暢。", "<strong>Set up before you play:</strong> Tapping \"Challenge\" opens a setup dialog where you pick the game mode (Square / Verse Rain / Voice Mode) and difficulty. In Voice Mode you can tick \"Do not repeat what I just recited\" for a faster flow.") }} /></li>
        </ul>

        <h2 style={{ borderBottom: '2px solid #e2e8f0', paddingBottom: '0.5rem', marginTop: '2rem' }}>{t("⚔️ 四、多人即時連線對戰", "⚔️ 4. Multiplayer Real-time Battle")}</h2>
        <p>{t("背經文不再是一個人孤單的事！", "Memorizing scripture is no longer a solitary task!")}</p>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '2rem' }}>
          <li><span dangerouslySetInnerHTML={{ __html: t("點下方的 <strong>「一起玩」</strong> 分頁創建專屬房間，邀請小組成員或家人一起加入。", "Open the <strong>\"Play\"</strong> tab at the bottom to create a private room and invite your group members or family to join.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("房主可以從全域經文組中挑選 <strong>「比賽經文」</strong>，並選擇比賽方式：獨立九宮格、雨滴瀑布或語音模式。", "The host picks the <strong>\"Competition Verses\"</strong> from the global verse bank and chooses how to play: Solo Square, Verse Rain, or Voice Mode.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>🌍 各自用自己的語言參賽（新）：</strong>在個人賽／邀人對戰 模式中，每位玩家都用自己選的聖經版本比賽——主持人用中文，朋友可以用英文 ESV 或韓文，同一節經文各自看到自己的語言。計分以節數與分數為準，與語言無關，完全公平。團隊競賽因為大家共用同一個盤面，維持主持人的語言。", "<strong>🌍 Everyone plays in their own language (new):</strong> In Solo / PK rooms each player competes in the Bible version they chose — the host in Chinese, a friend in English ESV or Korean — and everyone sees the same verse in their own language. Scoring is by verse count and points, independent of language, so it stays fair. Team battles share one board and therefore keep the host's language.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("所有人同時開始挑戰，並能在遊戲結束後看到即時的成績排行榜，非常適合主日學活動與小組破冰！", "Everyone starts the challenge simultaneously and can see real-time leaderboards after the game ends. Perfect for Sunday school activities and group icebreakers!") }} /></li>
        </ul>
        <ManualVideo src="/manual/multiplayer.mp4" poster="/manual/multiplayer.jpg" caption={t("教學影片：左邊是主持人（繁體中文）在經文組頁按「邀人對戰」開房；右邊是朋友把版本切成 English - ESV 後輸入代碼加入。比賽開始後，同一節經文各自看到自己的語言。", "Tutorial: on the left the host (Traditional Chinese) opens a room with \"Invite PK\" from the set page; on the right a friend switches to English - ESV and joins with the code. Once the match starts, each sees the same verse in their own language.")} />

        <h2 style={{ borderBottom: '2px solid #e2e8f0', paddingBottom: '0.5rem', marginTop: '2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Mic size={22} /> {t("五、親聲朗讀 — 用你自己的聲音讀經", "5. Read Aloud in Your Own Voice")}</h2>
        <p><span dangerouslySetInnerHTML={{ __html: t("在<strong>聆聽經文組</strong>時，你可以錄下自己的聲音來讀某一節。之後再聽這一節，聽到的就是你自己的聲音，而不是電腦語音；還能把它分享給朋友，讓他們也聽見你的親聲。", "While <strong>listening to a verse set</strong>, you can record your own voice reading a verse. Next time you play that verse you'll hear yourself instead of the computer voice — and you can share it so friends hear your voice too.") }} /></p>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '2rem' }}>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>錄下你的親聲：</strong>（需先登入）聆聽畫面下方那排按鈕中有一顆 🎙️ 麥克風鍵，點它、照著經文唸一遍、儲存即可。", "<strong>Record your voice:</strong> (login required) In the row of buttons at the bottom of the listen screen, tap the 🎙️ mic, read the verse aloud, and save.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>不只作者，人人都能錄：</strong>任何登入的玩家都可以為一節經文錄下自己的聲音並公開分享。打開播放器的「播放方式」→「聲音來源」，就能在 自動／電腦語音／無聲音／作者錄音／其他貢獻者的聲音 之間切換，聽聽弟兄姊妹怎麼讀這一節。", "<strong>Not just the author — anyone can record:</strong> Any signed-in player can record a verse in their own voice and share it publicly. Open the player's \"Play Mode\" → \"Voice\" to switch between Auto / Computer voice / No voice / Author / other contributors' voices and hear how brothers and sisters read the verse.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>播放優先順序：</strong>「自動」會優先播你自己的親聲，其次是最新公開的人聲，再來是經文組作者的親聲，最後才是電腦語音（TTS）。只要有人錄過，就不會聽到機器音。", "<strong>Playback priority:</strong> \"Auto\" plays your own voice first, then the newest public recording, then the set author's voice, and only then the computer voice (TTS). As long as someone has recorded, you never hear a robot.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>分享你正在聽的聲音：</strong>點 🔗 分享鍵，連結會帶著「你現在正在聽的那個聲音」——不論是你自己、作者或其他貢獻者的親聲，朋友打開連結聽到的就是同一個聲音。若錄音還在上傳，分享鍵會先等上傳完成再產生連結，確保對方一定聽得到。", "<strong>Share the voice you're listening to:</strong> Tap the 🔗 share button and the link carries whichever voice you're hearing right now — yours, the author's, or another contributor's — so your friend hears exactly the same voice. If a recording is still uploading, the button waits for it to finish before creating the link.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>暫停 / 繼續：</strong>播放親聲錄音時按暫停會停在原處，再按繼續會<strong>從原處接著播</strong>，不會從頭重讀。", "<strong>Pause / Resume:</strong> When a voice recording is playing, Pause holds the position and Resume <strong>continues from where it stopped</strong> instead of restarting.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>刪除：</strong>經文出處下方若顯示「🎙️ 這節有你的親聲」，點旁邊的「刪除 ✕」即可移除你的錄音，之後會回到作者的親聲或電腦語音。", "<strong>Delete:</strong> If \"🎙️ Your voice on this verse\" shows under the reference, tap \"Delete ✕\" next to it to remove your recording; playback then falls back to the author's or computer voice.") }} /></li>
        </ul>
        <div style={{ backgroundColor: '#eff6ff', borderLeft: '4px solid #3b82f6', padding: '1rem', borderRadius: '4px', marginBottom: '3rem' }}>
          <span dangerouslySetInnerHTML={{ __html: t("<strong>小提示：</strong>聆聽畫面上方中間、顯示日期或主題名稱的按鈕，下面寫著 <strong>【更多的主題經文】</strong> —— 點一下就能展開更多主題經文組，快速切換聆聽不同主題。", "<strong>Tip:</strong> The button at the top-center of the listen screen (showing the date or topic name) has <strong>[More topic verses]</strong> underneath — tap it to open more topic verse sets and switch quickly.") }} />
        </div>
        <h2 style={{ borderBottom: '2px solid #e2e8f0', paddingBottom: '0.5rem', marginTop: '2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Headphones size={22} /> {t("六、播放方式、我的最愛與更多聆聽小工具", "6. Play Mode, Favorites & More Listening Tools")}</h2>
        <p><span dangerouslySetInnerHTML={{ __html: t("聆聽畫面的 <strong>「播放方式」</strong> 視窗和幾顆新按鈕，讓連續聆聽更貼近你的習慣：", "The listen screen's <strong>\"Play Mode\"</strong> dialog and a few new buttons make continuous listening fit your routine:") }} /></p>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '2rem' }}>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>⏱️ 播放時間：</strong>可設定播放幾分鐘後自動停止，或無限循環播放——睡前、靈修時段都好用。", "<strong>⏱️ Duration:</strong> Set playback to stop after a number of minutes, or loop forever — handy at bedtime or during devotions.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>🔠 字體大小：</strong>同一個視窗裡可以調整聆聽畫面的字級，長輩或投影使用時把字放大更清楚。", "<strong>🔠 Font size:</strong> Adjust the text size of the listen screen in the same dialog — bigger for seniors or projection.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>⭐ 我的最愛：</strong>聆聽時點播放器上的星星，或在「我的經文組」的卡片上點星星，就能把經文組加入我的最愛。清單可用「我的最愛」排序，而且會跟著帳號同步到每一台裝置；從大廳「話語甘霖」進入後，也能直接挑「我的最愛」來聽。", "<strong>⭐ Favorites:</strong> Tap the star on the player, or on a card in \"My Custom Sets\", to add a verse set to your favorites. Sort the list by \"Favorites\", and they sync with your account across all devices. Entering from the lobby's \"Verse Rain\" card, you can pick \"Favorites\" to listen right away.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>🔄 雙語對調：</strong>讀經頁的「朗讀第二語言」按鈕會暫時把主／次語言互換，改用第二語言落字並朗讀，原語言退到下方小字；離開後自動還原，練習外語聽讀很方便。", "<strong>🔄 Swap languages:</strong> The reader's \"Read the second language\" button temporarily swaps your primary and secondary languages — the verse falls and is read aloud in the second language while the original shows below in small text. It reverts when you leave; great for practicing a foreign language.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>⚡ 邊聽邊挑戰：</strong>聆聽中按 ⚡ 立刻挑戰這一節；結束後按「返回朗讀」會回到同一節並暫停等你，按播放或 ‹ › 就能接著聽下一節。", "<strong>⚡ Challenge while listening:</strong> Tap ⚡ while listening to challenge the current verse. When it ends, \"Back to reading\" returns you to the same verse, paused; press Play or ‹ › to continue.") }} /></li>
        </ul>
        <ManualVideo src="/manual/play-mode.mp4" poster="/manual/play-mode.jpg" caption={t("教學影片：在經文組頁按「播放」→ 播放方式視窗設定播放時間、字體大小、聲音來源 → 選「按序」開始連續聆聽。", "Tutorial: press \"Play\" on a set page → set duration, font size and voice source in the Play Mode dialog → choose \"In Order\" to start continuous listening.")} />
        <ManualVideo src="/manual/listen.mp4" poster="/manual/listen.jpg" caption={t("教學影片：大廳「話語甘霖」→ 選「每日經文」或主題經文 → 按「朗讀」做雙語對調（改用第二語言朗讀）→ 按「切換聲音」選電腦語音、無聲音或親聲。", "Tutorial: lobby \"Verse Rain\" → pick \"Daily Verse\" or a topic → press \"Read\" to swap languages (read in the second language) → \"Switch voice\" to choose computer voice, no voice, or a recorded voice.")} />
        <h2 style={{ borderBottom: '2px solid #e2e8f0', paddingBottom: '0.5rem', marginTop: '2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Languages size={22} /> {t("七、經文組一鍵「翻譯」到其他語言", "7. Translate a Verse Set into Other Languages in One Click")}</h2>
        <p><span dangerouslySetInnerHTML={{ __html: t("辛苦建好的經文組，想給說別種語言的弟兄姊妹用？現在不必重打一次。", "Built a great verse set and want to share it with brothers and sisters who speak another language? No need to retype it.") }} /></p>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '2rem' }}>
          <li><span dangerouslySetInnerHTML={{ __html: t("在經文組詳情頁點 <strong>「翻譯」</strong>，選擇目標語言。系統會自動翻譯標題、把每節出處換成該語言的書名，並抓取<strong>該語言官方譯本的真實經文</strong>（不是機器翻譯的經文）。", "On a verse set's page tap <strong>\"Translate\"</strong> and pick a target language. The title is translated, each reference is converted to that language's book name, and the <strong>real text from that language's official Bible translation</strong> is fetched (not machine-translated scripture).") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("預覽畫面可以修改標題、逐節查看成功／失敗並重試；確認後點 <strong>「加入並編輯」</strong>，經文組就會發佈到該語言的經文組，並自動切換過去讓你補上簡介。", "In the preview you can edit the title, see each verse's success/failure and retry; then tap <strong>\"Add & Edit\"</strong> to publish it into that language's library, and the app switches over so you can add a description.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("VerseRain 現已支援 20 多種聖經版本與介面語言：繁／簡中文、台語、英文（KJV／ESV／NIV）、日文、韓文、西班牙文、葡萄牙文、法文、德文、俄文、印地文、阿拉伯文、波斯文、希伯來文、土耳其文、緬甸文、越南文、印尼文與馬來文——切換左上角的「版本」即可。", "VerseRain now supports 20+ Bible versions and interface languages: Traditional/Simplified Chinese, Taiwanese, English (KJV/ESV/NIV), Japanese, Korean, Spanish, Portuguese, French, German, Russian, Hindi, Arabic, Persian, Hebrew, Turkish, Burmese, Vietnamese, Indonesian and Malay — just switch \"Version\" at the top left.") }} /></li>
        </ul>
        <ManualVideo src="/manual/translate.mp4" poster="/manual/translate.jpg" caption={t("教學影片：在經文組頁按「翻譯」→ 選 Bahasa Melayu → 系統翻譯標題並抓取馬來文譯本 → 預覽 16 節全部成功 → 「加入並編輯」。", "Tutorial: press \"Translate\" on a set page → choose Bahasa Melayu → the title is translated and the Malay Bible text fetched → preview shows all 16 verses → \"Add & Edit\".")} />
        <h2 style={{ borderBottom: '2px solid #e2e8f0', paddingBottom: '0.5rem', marginTop: '2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Map size={22} /> {t("八、全球玩家地圖（2D／3D）", "8. Global Player Map (2D / 3D)")}</h2>
        <p><span dangerouslySetInnerHTML={{ __html: t("在下方的 <strong>「一起玩」</strong> 分頁點 <strong>「誰在玩」</strong>，看看世界各地的經文雨玩家都在哪裡。", "In the <strong>\"Play\"</strong> tab at the bottom, tap <strong>\"Who's Playing\"</strong> to see where VerseRain players are around the world.") }} /></p>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '2rem' }}>
          <li><span dangerouslySetInnerHTML={{ __html: t("點擊標記可以查看該玩家的成績；地圖上若有進行中的多人遊戲房間，<strong>雙擊房間就能直接加入戰局</strong>！", "Click a marker to see that player's scores; if a multiplayer room is open on the map, <strong>double-click it to jump straight into the battle</strong>!") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("右上角可在 <strong>「2D 地圖」</strong> 與 <strong>「3D 地球」</strong> 之間切換，轉動地球，看看全球背經的即時脈動。", "Switch between <strong>\"2D Map\"</strong> and <strong>\"3D Globe\"</strong> at the top right, spin the globe, and watch scripture memorization pulse around the world in real time.") }} /></li>
        </ul>
        <ManualVideo src="/manual/map.mp4" poster="/manual/map.jpg" caption={t("教學影片：點「誰在玩」看全球玩家分佈 → 按「3D 地球」→ 拖曳轉動地球。", "Tutorial: open \"Who's Playing\" to see players worldwide → press \"3D Globe\" → drag to spin the globe.")} />
        <h2 id="manual-score" style={{ borderBottom: '2px solid #e2e8f0', paddingBottom: '0.5rem', marginTop: '2rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Trophy size={22} /> {t("九、累積點數怎麼算？", "9. How Is My Total Score Calculated?")}</h2>
        <p>{t("累積點數跟著你的帳號走，登入後每一次挑戰、聆聽和每天回來讀經都會累積；改暱稱不會影響累積點數。", "Your total score belongs to your account: once you are signed in, every challenge, every verse you listen to and every day you come back to read counts, and changing your nickname never affects it.")}</p>
        <h3 style={{ marginTop: '1.5rem', color: '#0f172a' }}>{t("1. 每節經文，只算你最好的一次", "1. Each verse counts your best run only")}</h3>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '1.5rem' }}>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>第一次挑戰</strong>一節經文：這一局得幾分，累積點數就加幾分。", "<strong>First challenge</strong> of a verse: whatever you score is added in full.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>再挑戰同一節</strong>：只有超過你自己紀錄的部分會加進來。例如紀錄 800 分、這次 950 分，累積點數 +150；沒破紀錄就不加也不減。", "<strong>Replaying the same verse</strong>: only the part above your own record is added. Record 800, this run 950: +150. No new record means no change.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("<strong>挑戰失敗</strong>（生命耗盡）不計分。想讓累積點數長得快，就去挑戰還沒玩過的經文，或把舊經文的紀錄推高。", "<strong>A failed run</strong> (out of lives) does not count. To grow fast, challenge verses you have not played yet, or push your old records higher.") }} /></li>
        </ul>
        <h3 style={{ marginTop: '1.5rem', color: '#0f172a' }}>{t("2. 多人遊戲", "2. Multiplayer")}</h3>
        <p>{t("個人 PK 房間的成績跟單人挑戰一樣計入；團隊賽是課堂當場的比賽，不計入累積點數。", "Solo PK rooms count just like single-player challenges; team battles are live classroom events and do not count.")}</p>
        <h3 style={{ marginTop: '1.5rem', color: '#0f172a' }}>{t("3. 邀請朋友", "3. Inviting friends")}</h3>
        <p><span dangerouslySetInnerHTML={{ __html: t("朋友用你的推薦碼加入並第一次通過一節經文，你的累積點數 <strong>+5000</strong>，每位朋友一次。", "When a friend joins with your referral code and clears their first verse, your total points go up by <strong>+5000</strong>, once per friend.") }} /></p>
        <h3 style={{ marginTop: '1.5rem', color: '#0f172a' }}>{t("4. 每日登入", "4. Daily check-in")}</h3>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '1.5rem' }}>
          <li><span dangerouslySetInnerHTML={{ __html: t("當天<strong>聽完或挑戰完一節經文</strong>，就算這天有登入，會送出這天的登入分數（只打開 App 不算）。", "Listen to or challenge <strong>one verse to the end</strong> on a given day and that day counts as checked in; the check-in points are added then (just opening the app does not count).") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("連續登入的分數是 <strong>1000、1100、1200…最高 2000</strong>，連續第 12 天再從 1000 開始，11 天一輪。", "Consecutive days earn <strong>1000, 1100, 1200 … up to 2000</strong>; day 12 starts again at 1000, an 11-day cycle.") }} /></li>
          <li><span dangerouslySetInnerHTML={{ __html: t("每連續 7 天送一張<strong>「恩典日」</strong>（最多存 2 張）。漏掉的日子會自動用恩典日補上，連續天數不中斷（補上的那天沒有分數）；恩典日不夠補時，才從 1000 重來。", "Every 7 days in a row earns a <strong>grace day</strong> (up to 2 saved). A missed day is covered by a grace day automatically, so your streak continues (the covered day itself earns nothing); only when you run out of grace days does it start again at 1000.") }} /></li>
          <li>{t("依台灣時間（UTC+8）午夜換日。", "Days change at midnight Taiwan time (UTC+8).")}</li>
        </ul>
        <h3 style={{ marginTop: '1.5rem', color: '#0f172a' }}>{t("5. 聆聽經文", "5. Listening")}</h3>
        <p><span dangerouslySetInnerHTML={{ __html: t("在聆聽頁把一節經文<strong>聽完</strong>，累積點數 <strong>+100</strong>。同一節一天只算一次，一天最多 20 節（2000 分）。", "Listen to a verse <strong>to the end</strong> in the listening player and your total gets <strong>+100</strong>. Each verse counts once a day, up to 20 verses (2000 points) a day.") }} /></p>
        <h3 style={{ marginTop: '1.5rem', color: '#0f172a' }}>{t("6. 今日得分", "6. Today's score")}</h3>
        <p>{t("園子上方的「今日得分」就是今天新增的累積點數：新挑戰的經文、今天破紀錄的部分、每日登入和聆聽的分數，加上今天收到的推薦獎勵。", "\"Today's score\" at the top of your garden is what your total gained today: new verses, record improvements, check-in and listening points, and referral bonuses received today.")}</p>
        <h3 style={{ marginTop: '1.5rem', color: '#0f172a' }}>{t("7. 累積點數能做什麼？", "7. What can I do with it?")}</h3>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '1.5rem' }}>
          <li><span dangerouslySetInnerHTML={{ __html: t("點數可以在合作商家換取小額的消費折扣，也可以投入教會或機構的「愛心行動」。折扣由商家自願提供，<strong>實際能折多少，以產生折扣券時畫面上顯示的為準</strong>。點數是遊戲內無償取得的促銷權益：沒有現金價值、不能兌換現金、不能轉讓或轉售，也不是儲值或電子支付。可用點數 = 累積點數 − 已用點數；折抵只扣可用點數，累積點數不會減少。", "You can use points for a small discount at partner shops, or put them into a church or organisation’s “Love in Action” project. Discounts are offered voluntarily by the shops; <strong>the exact amount is shown on screen when you create a coupon</strong>. Points are a free in-game promotional benefit: they have no cash value, cannot be cashed out, transferred or resold, and are not stored value or e-payment. Available points = total score minus points already spent; a discount lowers your available points, never your total score.") }} /></li>
          <li>{t("每張折扣券最多折 NT$200、每人每月最多 NT$500；商家可另外設定每人每天可使用的張數。", "Each coupon is capped at NT$200 and each player at NT$500 per month; a shop may also set how many coupons one person can use per day.")}</li>
          <li>{t('點數聲明：點數是遊戲內無償取得的促銷折抵權益，無現金價值、不可兌換現金、不可轉讓或轉售，亦非儲值或電子支付；折扣由商家自行提供，經文雨不經手任何款項。', 'About points: points are a free in-game promotional discount right with no cash value; they cannot be cashed out, transferred or resold, and are not stored value or e-payment. Discounts are offered by the shops themselves; VerseRain never handles money.')}</li>
        </ul>
        <h3 style={{ marginTop: '1.5rem', color: '#0f172a' }}>{t("8. 和排行榜、園子的差別", "8. How it differs from the leaderboard and the garden")}</h3>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '2rem' }}>
          <li><span dangerouslySetInnerHTML={{ __html: t("排行榜依<strong>暱稱</strong>統計，累積點數依<strong>帳號</strong>統計；改過暱稱的話，排行榜上舊名字的分數不會搬過來，但累積點數完整保留。", "The leaderboard is tallied by <strong>nickname</strong>, the total score by <strong>account</strong>. If you renamed yourself, old-name leaderboard points stay where they are, but your total score is intact.") }} /></li>
          <li>{t("園子上的連續天數、樹和果子是成長紀錄，不是積分；每日登入分數另外依連續登入天數（台灣時間）計算。破紀錄會結果子，但果子不能折抵。", "The streak, trees and fruit in your garden are its growth record, not points; check-in points follow their own streak (Taiwan time). A new record bears fruit, but fruit cannot be redeemed.")}</li>
          <li>{t("沒登入只會上排行榜，不會計入帳號的累積點數，也不能用點數折抵；登入後從那一刻開始累積。", "Without signing in you only appear on the leaderboard: nothing is added to an account total and you cannot use points for a discount. Once signed in, it accumulates from that moment.")}</li>
        </ul>
        </div>
      </>
    </div>
  );
}
