// 題庫背景圖庫 — curated per-theme backgrounds a set creator can pick in
// the editor (set.background = 'preset:<id>'). Files live in
// public/set-backgrounds/ and are generated by
// scripts/generate-set-backgrounds.mjs; any of them can be replaced later
// with an AI-generated JPG/PNG by updating `url` here.

export const SET_BACKGROUND_THEMES = [
  { id: 'children', zh: '兒童', en: 'Children' },
  { id: 'elderly', zh: '長者', en: 'Elderly' },
  { id: 'family', zh: '家庭', en: 'Family' },
  { id: 'cross', zh: '十字架', en: 'Cross' },
  { id: 'nature', zh: '自然・創造', en: 'Nature' },
  { id: 'healing', zh: '醫治', en: 'Healing' },
  { id: 'peace', zh: '平安', en: 'Peace' },
  { id: 'worship', zh: '敬拜・讚美', en: 'Worship' },
  { id: 'prayer', zh: '禱告', en: 'Prayer' },
  { id: 'light', zh: '光・興起發光', en: 'Light' },
  { id: 'harvest', zh: '豐收・果實', en: 'Harvest' },
  { id: 'shepherd', zh: '牧人・詩篇23', en: 'Shepherd' },
].map(themeEntry => ({ ...themeEntry, url: `/set-backgrounds/${themeEntry.id}.svg` }));

// 'preset:<id>' → URL, or null when unset/unknown (caller falls back to
// the default rotating AI backgrounds).
export function getSetBackgroundUrl(background) {
  const raw = String(background || '');
  if (!raw.startsWith('preset:')) return null;
  const id = raw.slice('preset:'.length);
  const found = SET_BACKGROUND_THEMES.find(themeEntry => themeEntry.id === id);
  return found ? found.url : null;
}
