// Proverbs 1-30 in Chinese (Traditional), English (KJV), Korean, and Japanese
// Each chapter = one verse entry, intended for Rain Mode one-chapter-per-game

// ── Chinese (Traditional / CUV) ──────────────────────────────────────────────
export const VERSE_SETS_PROVERBS_ZH = [
  {
    id: "proverbs-zh",
    title: "箴言 1–30",
    description: "箴言一至三十章，每章一局，適合「經文雨」逐章背誦挑戰。",
    verses: [
      { id: "prv-zh-1",  reference: "箴言 1", title: "箴言第一章",  text: "以色列王大衛的兒子所羅門的箴言。要知道智慧和訓誨，要分辨通達的言語，要領受智慧、仁義、公平、正直的訓誨，使愚人靈明，使少年人有知識和謀略。使智慧人聽見，增長學問，使聰明人得著智謀，使人明白箴言和譬喻，明白智慧人的言詞和謎語。敬畏耶和華是知識的開端，愚妄人藐視智慧和訓誨。我兒，要聽你父親的訓誨，不可離棄你母親的法則，因為這些要在你頭上增添嘉冕，為你頸給加彩鏈。我兒，惡人若引誘你，你不可隨從。" },
      { id: "prv-zh-2",  reference: "箴言 2", title: "箴言第二章",  text: "我兒，你若領受我的言語，存記我的命令，側耳聽智慧，專心求聰明，呼求明哲，揚聲求聰明，尋找它，如尋找銀子，搜求它，如搜求隱藏的珍寶，你就明白敬畏耶和華，得以認識神。因為耶和華賜人智慧，知識和聰明都由他口而出。他給正直人存留真智慧，給行為純正的人作盾牌，為要保守公平人的路，護庇虔敬人的道。" },
      { id: "prv-zh-3",  reference: "箴言 3", title: "箴言第三章",  text: "我兒，不要忘記我的法則，你心要謹守我的誡命，因為它必將長久的日子、生命的年數，與平安，加給你。不可使慈愛、誠實離開你，要繫在你頸上，刻在你心版上。這樣，你必在神和世人眼前蒙恩寵，有聰明。你要專心仰賴耶和華，不可倚靠自己的聰明，在你一切所行的事上都要認定他，他必指引你的路。不可自以為有智慧，要敬畏耶和華，遠離惡事。這便醫治你的肚臍，滋潤你的骨頭。你要以財物，和一切初熟的土產，尊榮耶和華。這樣，你的倉房，必充滿有餘，你的酒醡，有新酒盈溢。" },
      { id: "prv-zh-4",  reference: "箴言 4", title: "箴言第四章",  text: "眾子啊，要聽父親的訓誨，留心得知聰明。因我所給你們的是好教訓，不可離棄我的法則。我在父親面前為孝子，在母親眼中為獨一愛子。父親教訓我說：我兒，你要心存我的言語，遵守我的命令，便得存活。要得智慧，要得聰明，不可忘記，也不可偏離我口中的言語。不可離棄智慧，智慧就護衛你，要愛她，她就保守你。智慧為首，所以要得智慧，用你一切所得的，換取聰明。" },
      { id: "prv-zh-5",  reference: "箴言 5", title: "箴言第五章",  text: "我兒，要留心我的智慧，側耳聽我的聰明，為要保守謀略，使你的嘴謹守知識。因為淫婦的嘴滴下蜂蜜，她的口比油更滑；末後卻苦似茵蔯，快如兩刃的刀。你當遠離她，不可就近她的房門，恐怕你把尊榮給了別人，把歲月給了殘忍的人。你要喜樂，就是與你年幼所娶的妻。她如可愛的麀鹿，可娛的母鹿，願她的胸懷使你時時知足，她的愛情使你常常戀慕。我兒，你為何戀慕淫婦，為何抱外女的胸懷？" },
      { id: "prv-zh-6",  reference: "箴言 6", title: "箴言第六章",  text: "我兒，你若為朋友作保，替外人擊掌，你若被自己口中的話語纏住，被自己口中的話語捆綁，你就當照我說的行，可以救自己，因你落在朋友手中，你去要自卑，去懇求你的朋友。懶惰人哪，你去察看螞蟻的動作，就可以得智慧。螞蟻沒有元帥、官長、君王，尚且在夏天預備食物，在收割時聚斂糧食。耶和華所恨惡的有六樣，連他心所憎惡的共有七樣：就是高傲的眼，撒謊的舌，流無辜人血的手，圖謀惡計的心，飛跑行惡的腳，吐謊言的假見證，並弟兄中布散紛爭的人。" },
      { id: "prv-zh-7",  reference: "箴言 7", title: "箴言第七章",  text: "我兒，你要遵守我的言語，將我的命令存記在心。遵守我的命令就得存活，保護我的法則好像保護眼中的瞳仁。要繫在你指頭上，刻在你心版上。對智慧說，你是我的姊妹，稱呼聰明為你的親人，她就能保守你遠離淫婦，遠離說諂媚話的外女。好色的人動心，設在街上的淫婦話語甜蜜，引誘少年人，勸他跟從，他就跟著她去，如同牛往宰殺之地，你要聽從我說的話，存記我的命令。" },
      { id: "prv-zh-8",  reference: "箴言 8", title: "箴言第八章",  text: "智慧豈不呼叫，聰明豈不發聲？她在道旁高處的頂上，在十字路口站立，在城門旁，在城門口，在城門洞大聲說：眾人哪，我呼叫你們，我向世人發聲。論到我，智慧，我住在謹慎那裡，我尋得知識和謀略。耶和華在太初創造萬物之先，在亙古之始就有了我。從亙古，從太初，未有大地以前，我已被立。沒有深淵，沒有大水源的時候，我已生出。那時，我在他那裡為工匠，日日為他所喜愛，常常在他面前歡樂，歡樂在他為人預備可住之地，也喜悅住在世人之間。" },
      { id: "prv-zh-9",  reference: "箴言 9", title: "箴言第九章",  text: "智慧建造房屋，鑿成七根柱子，宰殺牲畜，調和旨酒，設擺筵席，打發使女出去，在城中最高處呼叫，說：誰是愚蒙人，可以轉到這裡來！又對那無知的人說：你們來，吃我的餅，喝我調和的酒。你們愚蒙人，要捨棄愚蒙，就得存活，並要走光明的道路。嘲笑人的，若責備他，必受羞辱，責備惡人的，必被玷污。不要責備褻慢人，恐怕他恨你；要責備智慧人，他必愛你。教導智慧人，他就更有智慧；指示義人，他就增長學問。敬畏耶和華是智慧的開端，認識至聖者便是聰明。" },
      { id: "prv-zh-10", reference: "箴言 10", title: "箴言第十章",  text: "智慧的兒子使父親歡樂，愚昧的兒子叫母親憂愁。不義之財毫無益處，惟有公義能救人脫離死亡。耶和華不使義人受飢餓，卻阻止惡人所貪想的。手懶的，要受貧窮，手勤的，卻要富足。夏日聚斂的，是智慧之子，收割時沉睡的，是貽羞之子。義人的記念被稱讚，惡人的名字必朽爛。心中智慧的，必受命令，口多妄言的，必至敗亡。恨藏人的，嘴多謊言，愛好傷人的，必多恥辱。誡命是燈，法則是光，訓誨的責備，是生命的道。" },
      { id: "prv-zh-11", reference: "箴言 11", title: "箴言第十一章", text: "詭詐的天平，為耶和華所憎惡，公平的法碼，為他所喜悅。驕傲來，羞辱也來，謙遜人卻有智慧。正直人的純正，必引導自己，奸詐人的乖僻，必毀滅自己。有施散的，卻更增添；有吝嗇過度的，反致窮乏。好施捨的，必得豐裕；滋潤人的，必得滋潤。囤積糧食的，民必咒詛他；出售糧食的，必有福在他的頭上。仁義的果效是生命，以忿恨待人的，是要死亡。城必因正直人的祝福而興旺，卻因惡人的口而傾覆。" },
      { id: "prv-zh-12", reference: "箴言 12", title: "箴言第十二章", text: "喜愛管教的，就是喜愛知識，恨惡責備的，卻是畜類。善人必蒙耶和華的恩惠，設謀惡事的人，耶和華必定他的罪。人靠惡事，站立不住，義人的根，必不動搖。才德的婦人，是丈夫的冠冕，貽羞的婦人，如同朽爛在她丈夫的骨中。義人的思念，是公平，惡人的計謀，是詭詐。惡人的話語，是埋伏流人血，正直人的口，必解救人。懶惰人所想念的叫自己受苦，因為他的手拒絕做工。" },
      { id: "prv-zh-13", reference: "箴言 13", title: "箴言第十三章", text: "智慧的兒子聽父親的教訓，褻慢人不聽責備。人因口所結的果子，必享美福，奸詐人所渴慕的，是強暴。謹守口的，得保生命，大張嘴的，必至敗亡。勤勞人的手必掌權，懶惰的人必服苦。義人的光明亮，惡人的燈，必熄滅。驕傲只啟爭競，聽勸言的，卻有智慧。不義而得之財，必消耗，那以手聚斂的，必見增添。希望遲延，令人心憂，所願意的臨到，卻是生命樹。" },
      { id: "prv-zh-14", reference: "箴言 14", title: "箴言第十四章", text: "智慧婦人，建立家室，愚妄婦人，親手拆毀。行事正直的，敬畏耶和華，行事乖僻的，藐視他。愚妄人的口，以驕傲為杖，智慧人的嘴，保護自己。沒有牛，槽枥潔淨，土產豐盛，卻靠牛力。誠實見證人，不說謊言，假見證人，吐出謊言。褻慢人尋智慧，卻尋不著，聰明人知識甚易。敬畏耶和華，是生命的泉源，可以使人離開死亡的網羅。王的榮耀在乎民多，君侯衰敗在乎民少。不輕易發怒的，大有聰明，性情暴躁的，大顯愚妄。" },
      { id: "prv-zh-15", reference: "箴言 15", title: "箴言第十五章", text: "回答柔和，使怒消退，言語暴戾，觸動怒氣。智慧人的舌，善發知識，愚昧人的口，吐出愚昧。耶和華的眼目，無處不在，惡人善人，他都鑒察。溫良的舌，是生命樹，乖謬的嘴，使人心碎。愚妄人藐視父親的管教，領受責備的，得著謹慎。義人的家中，多有財寶，惡人的進項，是惡事。智慧人的嘴，播揚知識，愚昧人的心，並不如此。敬畏耶和華，是智慧的訓誨，尊榮以前，必有謙遜。舍少業，敬畏耶和華，強過多聚財，煩亂不安。" },
      { id: "prv-zh-16", reference: "箴言 16", title: "箴言第十六章", text: "心中的謀算，在乎人，舌頭的答言，由於耶和華。人一切所行的路，在自己眼中都看為清潔，惟有耶和華衡量人心。你所做的事，要交託耶和華，你所謀的，就必成立。耶和華為自己造萬物，連惡人也為禍患的日子所造。驕傲在敗壞以先，狂心在跌倒之前。心中謙遜與貧窮人來往，強如將擄物與驕傲人同分。謹慎思量道路，才知進退，這是聰明。" },
      { id: "prv-zh-17", reference: "箴言 17", title: "箴言第十七章", text: "一塊乾餅，彼此相安，強如祭肉滿屋，彼此相爭。聰明的僕人，必管轄貽羞之子，在眾弟兄中，也必分受產業。鼎為煉銀，爐為煉金，惟有耶和華熬煉人心。行惡的，留心聽謊言的嘴，說謊的，側耳聽奸惡的舌頭。嘲笑窮人的，是辱沒造他的主，幸災樂禍的，必不免受罰。子孫是老人的冠冕，父親是兒女的榮耀。有德言語，不合愚妄人，何況謊言，不合尊貴人。不當的時候，告別朋友的臉，如同人拿食物給朋友，後來把它奪回。" },
      { id: "prv-zh-18", reference: "箴言 18", title: "箴言第十八章", text: "與人離群，獨居的，是尋求私慾，並惱恨一切真智慧。愚昧人不喜愛明哲，只喜愛顯露心意。惡人來，藐視也來，羞辱也與辱罵俱來。人口中的言語，如同深水，智慧的泉源，如同湧流的河水。容貌偏護惡人，乃是不好的，這案件使人偏枉正直，也是不好的。愚昧人的嘴，自取敗壞，他的嘴唇，是他靈魂的網羅。讒謗人的言語，如同美食，深入人的心腹。懶惰度日的，是浪費之弟兄。耶和華的名，是堅固台，義人奔入便得安全。" },
      { id: "prv-zh-19", reference: "箴言 19", title: "箴言第十九章", text: "行事純正中，雖窮乏，勝過乖謬，雖富足。心無知識，不善，腳步急快，失途了。人的愚昧傾敗他的路，他的心也抱怨耶和華。財物使朋友增多，但窮人與朋友離絕。假見證人，不免受罰，吐謊言的，也必滅亡。養尊處優的兒子，所求的不好；偷懶的兒子，必貽父羞恥。房屋錢財，是祖宗所遺留的，但賢慧的妻，是耶和華所賜的。懶惰人沉靜睡覺，是自害，懶惰的，必受飢餓。憐憫貧窮的，就是借給耶和華，他的善行，耶和華必償還。管教你的兒子，他就使你得安息，也使你心裡喜悅。" },
      { id: "prv-zh-20", reference: "箴言 20", title: "箴言第二十章", text: "酒能使人褻慢，濃酒使人喧嚷，凡因酒而差錯的，就不是有智慧的。王的威嚴，如同幼獅吼叫，惹動他怒的，是自害己命。爭訟遠離的，是自己的榮耀；所以愚昧人都愛爭訟。懶惰人因冬寒不肯耕種，到收割的時候，他必討飯，無所得。人心中的謀算，如同深水，惟有聰明人，才能汲取出來。人多述說自己的仁慈，但忠信人誰能尋到呢？" },
      { id: "prv-zh-21", reference: "箴言 21", title: "箴言第二十一章", text: "王的心在耶和華手中，好像田間的水溝，隨意流轉。人所行的路，自己眼中都看為正，惟有耶和華衡量人心。行公義公平，比獻祭更蒙耶和華悅納。眼目高傲，心中狂妄，乃是罪惡，都是惡人所發出的。謹慎人的謀略，有利可圖，魯莽人的急性，有虧損可知。賢慧的妻，是耶和華所賜的。懶惰人渴想，卻無所得，殷勤人必得豐裕。義人有所拒絕施捨，惡人所施捨的，反為罪惡。" },
      { id: "prv-zh-22", reference: "箴言 22", title: "箴言第二十二章", text: "美名勝過大財，恩寵強如金銀。富戶窮人在世相遇，都是耶和華所造的。聰明人見禍藏躲，愚蒙人卻往前行，受其害。謙遜，敬畏耶和華的報酬，就是財富、尊榮，並生命。你要立志訓練孩童，走當行的道，就是到老他也不偏離。你當留心細聽有智慧人的言語，歸心於我的知識，這事使你知道，言語準確的實情，你好將真實話回答那差你來問的人。" },
      { id: "prv-zh-23", reference: "箴言 23", title: "箴言第二十三章", text: "你若坐下與官長吃飯，要留意在你面前的是誰。若你是貪食的，就當拿刀放在喉嚨上。不要貪戀他的美食，因為這食物是哄誘你的。不要勞苦求富，休仗自己的聰明。你豈要定眼在虛無的錢財上呢？錢財必長翅膀，如鷹向天飛去。你不要吃惡眼人的飯，也不要貪他的美味，因為他心怎樣思量，他為人就是怎樣，他雖對你說，請吃請喝，他的心卻與你相背。你不要挪移古時的地界，也不要侵入孤兒的田地。訓練孩童走當行的道，就是到老他也不偏離。" },
      { id: "prv-zh-24", reference: "箴言 24", title: "箴言第二十四章", text: "不要嫉妒惡人，也不要想與他們在一起，因為他們心裡謀害，他們的嘴說的是患難。家藉智慧建造，又藉聰明立穩，其中因知識充滿各樣寶貴，美好的財物。智慧人大有能力，有知識的人，力上加力。你與仇敵相遇，若他飢餓，就給他食物吃；若他口渴，就給他水喝；因為你這樣行，就是把炭火堆在他頭上，耶和華也必賞賜你。不要因惡人得志，心裡妒忌，也不要嫉妒惡人。" },
      { id: "prv-zh-25", reference: "箴言 25", title: "箴言第二十五章", text: "這也是所羅門的箴言，是猶大王希西家的人所謄錄的。將事遮隱，乃神的榮耀，將事察清，乃君王的榮耀。天的高，地的深，君王的心，都不可測透。你在王面前，不要自誇，也不要站在大人的地方，因為寧可有人說，請你上來，強如在你覲見的王子面前叫你退下。你的腳不要輕易地上鄰舍的家，恐怕他厭煩你，恨惡你。話語說得合宜，就如金蘋果在銀網子裡。及時的一句話，就如耳環和精金的妝飾，對聽從的人說。" },
      { id: "prv-zh-26", reference: "箴言 26", title: "箴言第二十六章", text: "夏天降雪，收割時下雨，都不相宜，照樣，尊榮愚昧人也不相宜。麻雀往來飛翔，燕子翩翩而飛，這樣，無故的咒詛，必不臨頭。無論何災，都不降在義人身上，但惡人滿受禍患。懶惰人說，路上有獅子，街上有猛獅。門在鉸鏈上轉動，懶惰人在床上也是如此。懶惰人把手插在碗裡，就是向口舉手，他也以為勞累。聰明人眼中所見的，愚昧人也以為是聰明的。" },
      { id: "prv-zh-27", reference: "箴言 27", title: "箴言第二十七章", text: "不要為明日自誇，因為一日要生何事，你尚且不能知道。要別人誇讚你，不可用口自誇；等外人稱讚你，不可用嘴自稱。石頭重，沙土沉，愚妄人的惱怒，比這兩樣都更重。忿怒是殘忍的，怒氣如狂瀾，嫉妒的心，誰能敵得住呢？當面的責備，強如背後的愛情。忠誠人的傷痕，出於忠誠，仇敵人的多嘴，就是讒謗。人捨本家，飄流在外，好像雀鳥離巢而飛。" },
      { id: "prv-zh-28", reference: "箴言 28", title: "箴言第二十八章", text: "惡人雖無人追趕，也逃跑；義人卻膽壯，如獅子。因國中有罪，執政者就多，惟有聰明人，靠知識得久治。貧窮人欺壓弱者，好像暴雨沖沒糧食。棄掉律法的，誇獎惡人；守住律法的，卻與惡人相爭。惡人不明白公義，但尋求耶和華的，什麼都明白。寧可行事純正，家道貧窮，強如行事乖僻，家道富足。守律法的，是智慧之子，與貪食人作伴的，卻羞辱其父。" },
      { id: "prv-zh-29", reference: "箴言 29", title: "箴言第二十九章", text: "人屢次受責罰，仍然頸硬，他必忽然敗壞，無法可治。義人增多，民就喜樂；惡人掌權，民就歎息。喜愛智慧的，使父親歡樂；與妓女結交的，卻枉費錢財。王藉公平，使國堅立；索要賄賂的，使國傾覆。諂媚鄰舍的，就是設網羅絆他的腳。惡人犯罪，有網羅陷住他；義人都歌唱而喜樂。義人關心窮人的案件，惡人毫不理會。褻慢人煽惑通城，但智慧人止息眾怒。管教你的兒子，他就給你安慰，也給你心裡的喜悅。" },
      { id: "prv-zh-30", reference: "箴言 30", title: "箴言第三十章", text: "雅基的兒子亞古珥有神諭說：我是最愚昧的人，沒有人的聰明，我也沒有學會智慧的知識，也不認識至聖者。誰升天又降下來呢？誰聚風在掌中呢？誰包水在衣服裡呢？誰立定地的四極呢？他名叫什麼？他兒子名叫什麼？你知道嗎？神的言語句句都是煉淨的，投靠他的，他是盾牌。他的言語，你不可加添，恐怕他責備你，你就算為說謊言的。有貧窮人用刀殺戮惡人的事，這世界不能容他。螞蟻是無力之類，卻在夏天預備糧食。蒺藜鼠是軟弱之類，卻在磐石中造牠的房屋。蝗蟲沒有君王，卻分隊而行。" },
    ]
  }
];

// ── English (KJV) ─────────────────────────────────────────────────────────────
export const VERSE_SETS_PROVERBS_KJV = [
  {
    id: "proverbs-kjv",
    title: "Proverbs 1–30 (KJV)",
    description: "Proverbs chapters 1–30, one chapter per round — perfect for Rain Mode chapter-by-chapter memorization.",
    verses: [
      { id: "prv-kjv-1",  reference: "Proverbs 1", title: "Proverbs Chapter 1",  text: "The proverbs of Solomon the son of David, king of Israel; To know wisdom and instruction; to perceive the words of understanding; To receive the instruction of wisdom, justice, and judgment, and equity; To give subtilty to the simple, to the young man knowledge and discretion. A wise man will hear, and will increase learning; and a man of understanding shall attain unto wise counsels. The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction. My son, hear the instruction of thy father, and forsake not the law of thy mother: For they shall be an ornament of grace unto thy head, and chains about thy neck. My son, if sinners entice thee, consent thou not." },
      { id: "prv-kjv-2",  reference: "Proverbs 2", title: "Proverbs Chapter 2",  text: "My son, if thou wilt receive my words, and hide my commandments with thee; So that thou incline thine ear unto wisdom, and apply thine heart to understanding; Yea, if thou criest after knowledge, and liftest up thy voice for understanding; If thou seekest her as silver, and searchest for her as for hid treasures; Then shalt thou understand the fear of the LORD, and find the knowledge of God. For the LORD giveth wisdom: out of his mouth cometh knowledge and understanding. He layeth up sound wisdom for the righteous: he is a buckler to them that walk uprightly." },
      { id: "prv-kjv-3",  reference: "Proverbs 3", title: "Proverbs Chapter 3",  text: "My son, forget not my law; but let thine heart keep my commandments: For length of days, and long life, and peace, shall they add to thee. Let not mercy and truth forsake thee: bind them about thy neck; write them upon the table of thine heart: So shalt thou find favour and good understanding in the sight of God and man. Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths. Be not wise in thine own eyes: fear the LORD, and depart from evil. Honour the LORD with thy substance, and with the firstfruits of all thine increase: So shall thy barns be filled with plenty, and thy presses shall burst out with new wine." },
      { id: "prv-kjv-4",  reference: "Proverbs 4", title: "Proverbs Chapter 4",  text: "Hear, ye children, the instruction of a father, and attend to know understanding. For I give you good doctrine, forsake ye not my law. For I was my father's son, tender and only beloved in the sight of my mother. He taught me also, and said unto me, Let thine heart retain my words: keep my commandments, and live. Get wisdom, get understanding: forget it not; neither decline from the words of my mouth. Forsake her not, and she shall preserve thee: love her, and she shall keep thee. Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding. Keep thy heart with all diligence; for out of it are the issues of life." },
      { id: "prv-kjv-5",  reference: "Proverbs 5", title: "Proverbs Chapter 5",  text: "My son, attend unto my wisdom, and bow thine ear to my understanding: That thou mayest regard discretion, and that thy lips may keep knowledge. For the lips of a strange woman drop as an honeycomb, and her mouth is smoother than oil: But her end is bitter as wormwood, sharp as a twoedged sword. Remove thy way far from her, and come not nigh the door of her house: Let thy fountain be blessed: and rejoice with the wife of thy youth. Let her be as the loving hind and pleasant roe; let her breasts satisfy thee at all times; and be thou ravished always with her love." },
      { id: "prv-kjv-6",  reference: "Proverbs 6", title: "Proverbs Chapter 6",  text: "My son, if thou be surety for thy friend, if thou hast stricken thy hand with a stranger, Thou art snared with the words of thy mouth, thou art taken with the words of thy mouth. Go to the ant, thou sluggard; consider her ways, and be wise: Which having no guide, overseer, or ruler, Provideth her meat in the summer, and gathereth her food in the harvest. These six things doth the LORD hate: yea, seven are an abomination unto him: A proud look, a lying tongue, and hands that shed innocent blood, A heart that deviseth wicked imaginations, feet that be swift in running to mischief, A false witness that speaketh lies, and he that soweth discord among brethren." },
      { id: "prv-kjv-7",  reference: "Proverbs 7", title: "Proverbs Chapter 7",  text: "My son, keep my words, and lay up my commandments with thee. Keep my commandments, and live; and my law as the apple of thine eye. Bind them upon thy fingers, write them upon the table of thine heart. Say unto wisdom, Thou art my sister; and call understanding thy kinswoman: That they may keep thee from the strange woman, from the stranger which flattereth with her words. For at the window of my house I looked through my casement, And beheld among the simple ones, I discerned among the youths, a young man void of understanding." },
      { id: "prv-kjv-8",  reference: "Proverbs 8", title: "Proverbs Chapter 8",  text: "Doth not wisdom cry? and understanding put forth her voice? She standeth in the top of high places, by the way in the places of the paths. She crieth at the gates, at the entry of the city, at the coming in at the doors. The LORD possessed me at the beginning of his work, the first of his acts of old. Ages ago I was set up, at the first, before the beginning of the earth. Then I was beside him, like a master workman, and I was daily his delight, rejoicing before him always, rejoicing in his inhabited world and delighting in the children of man." },
      { id: "prv-kjv-9",  reference: "Proverbs 9", title: "Proverbs Chapter 9",  text: "Wisdom hath builded her house, she hath hewn out her seven pillars: She hath killed her beasts; she hath mingled her wine; she hath also furnished her table. Forsake the foolish, and live; and go in the way of understanding. He that reproveth a scorner getteth to himself shame: and he that rebuketh a wicked man getteth himself a blot. Reprove not a scorner, lest he hate thee: rebuke a wise man, and he will love thee. Give instruction to a wise man, and he will be yet wiser: teach a just man, and he will increase in learning. The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding." },
      { id: "prv-kjv-10", reference: "Proverbs 10", title: "Proverbs Chapter 10", text: "A wise son maketh a glad father: but a foolish son is the heaviness of his mother. Treasures of wickedness profit nothing: but righteousness delivereth from death. The LORD will not suffer the soul of the righteous to famish: but he casteth away the substance of the wicked. He becometh poor that dealeth with a slack hand: but the hand of the diligent maketh rich. He that gathereth in summer is a wise son: but he that sleepeth in harvest is a son that causeth shame. The memory of the just is blessed: but the name of the wicked shall rot." },
      { id: "prv-kjv-11", reference: "Proverbs 11", title: "Proverbs Chapter 11", text: "A false balance is abomination to the LORD: but a just weight is his delight. When pride cometh, then cometh shame: but with the lowly is wisdom. The integrity of the upright shall guide them: but the perverseness of transgressors shall destroy them. There is that scattereth, and yet increaseth; and there is that withholdeth more than is meet, but it tendeth to poverty. The liberal soul shall be made fat: and he that watereth shall be watered also himself. He that withholdeth corn, the people shall curse him: but blessing shall be upon the head of him that selleth it." },
      { id: "prv-kjv-12", reference: "Proverbs 12", title: "Proverbs Chapter 12", text: "Whoso loveth instruction loveth knowledge: but he that hateth reproof is brutish. A good man obtaineth favour of the LORD: but a man of wicked devices will he condemn. A virtuous woman is a crown to her husband: but she that maketh ashamed is as rottenness in his bones. The thoughts of the righteous are right: but the counsels of the wicked are deceit. A righteous man regardeth the life of his animal, but the mercy of the wicked is cruel. Diligence is man's precious possession." },
      { id: "prv-kjv-13", reference: "Proverbs 13", title: "Proverbs Chapter 13", text: "A wise son heareth his father's instruction: but a scorner heareth not rebuke. A man shall eat good by the fruit of his mouth: but the soul of the transgressors shall eat violence. He that keepeth his mouth keepeth his life: but he that openeth wide his lips shall have destruction. The soul of the sluggard desireth, and hath nothing: but the soul of the diligent shall be made fat. Hope deferred maketh the heart sick: but when the desire cometh, it is a tree of life." },
      { id: "prv-kjv-14", reference: "Proverbs 14", title: "Proverbs Chapter 14", text: "Every wise woman buildeth her house: but the foolish plucketh it down with her hands. He that walketh in his uprightness feareth the LORD: but he that is perverse in his ways despiseth him. In the mouth of the foolish is a rod of pride: but the lips of the wise shall preserve them. The fear of the LORD is a fountain of life, to depart from the snares of death. In the multitude of people is the king's honour: but in the want of people is the destruction of the prince. He that is slow to wrath is of great understanding: but he that is hasty of spirit exalteth folly." },
      { id: "prv-kjv-15", reference: "Proverbs 15", title: "Proverbs Chapter 15", text: "A soft answer turneth away wrath: but grievous words stir up anger. The tongue of the wise useth knowledge aright: but the mouth of fools poureth out foolishness. The eyes of the LORD are in every place, beholding the evil and the good. A wholesome tongue is a tree of life: but perverseness therein is a breach in the spirit. Better is little with the fear of the LORD than great treasure and trouble therewith. The fear of the LORD is the instruction of wisdom; and before honour is humility." },
      { id: "prv-kjv-16", reference: "Proverbs 16", title: "Proverbs Chapter 16", text: "The preparations of the heart in man, and the answer of the tongue, is from the LORD. All the ways of a man are clean in his own eyes; but the LORD weigheth the spirits. Commit thy works unto the LORD, and thy thoughts shall be established. Pride goeth before destruction, and an haughty spirit before a fall. Better it is to be of an humble spirit with the lowly, than to divide the spoil with the proud. A man's heart deviseth his way: but the LORD directeth his steps." },
      { id: "prv-kjv-17", reference: "Proverbs 17", title: "Proverbs Chapter 17", text: "Better is a dry morsel, and quietness therewith, than an house full of sacrifices with strife. The fining pot is for silver, and the furnace for gold: but the LORD trieth the hearts. A friend loveth at all times, and a brother is born for adversity. A merry heart doeth good like a medicine: but a broken spirit drieth the bones. Even a fool, when he holdeth his peace, is counted wise: and he that shutteth his lips is esteemed a man of understanding." },
      { id: "prv-kjv-18", reference: "Proverbs 18", title: "Proverbs Chapter 18", text: "Through desire a man, having separated himself, seeketh and intermeddleth with all wisdom. A fool hath no delight in understanding, but that his heart may discover itself. The words of a man's mouth are as deep waters, and the wellspring of wisdom as a flowing brook. The name of the LORD is a strong tower: the righteous runneth into it, and is safe. A man's gift maketh room for him, and bringeth him before great men. Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof." },
      { id: "prv-kjv-19", reference: "Proverbs 19", title: "Proverbs Chapter 19", text: "Better is the poor that walketh in his integrity, than he that is perverse in his lips, and is a fool. Wealth maketh many friends; but the poor is separated from his neighbour. A false witness shall not be unpunished, and he that speaketh lies shall perish. House and riches are the inheritance of fathers: and a prudent wife is from the LORD. He that hath pity upon the poor lendeth unto the LORD; and that which he hath given will he pay him again. Chasten thy son while there is hope, and let not thy soul spare for his crying." },
      { id: "prv-kjv-20", reference: "Proverbs 20", title: "Proverbs Chapter 20", text: "Wine is a mocker, strong drink is raging: and whosoever is deceived thereby is not wise. The king's wrath is as the roaring of a lion: whoso provoketh him to anger sinneth against his own soul. The sluggard will not plow by reason of the cold; therefore shall he beg in harvest, and have nothing. Counsel in the heart of man is like deep water; but a man of understanding will draw it out. Most men will proclaim every one his own goodness: but a faithful man who can find?" },
      { id: "prv-kjv-21", reference: "Proverbs 21", title: "Proverbs Chapter 21", text: "The king's heart is in the hand of the LORD, as the rivers of water: he turneth it whithersoever he will. Every way of a man is right in his own eyes: but the LORD pondereth the hearts. To do justice and judgment is more acceptable to the LORD than sacrifice. Whoso keepeth his mouth and his tongue keepeth his soul from troubles. The desire of the slothful killeth him; for his hands refuse to labour. He that loveth pleasure shall be a poor man: he that loveth wine and oil shall not be rich." },
      { id: "prv-kjv-22", reference: "Proverbs 22", title: "Proverbs Chapter 22", text: "A good name is rather to be chosen than great riches, and loving favour rather than silver and gold. The rich and poor meet together: the LORD is the maker of them all. A prudent man foreseeth the evil, and hideth himself: but the simple pass on, and are punished. By humility and the fear of the LORD are riches, and honour, and life. Train up a child in the way he should go: and when he is old, he will not depart from it." },
      { id: "prv-kjv-23", reference: "Proverbs 23", title: "Proverbs Chapter 23", text: "When thou sittest to eat with a ruler, consider diligently what is before thee: And put a knife to thy throat, if thou be a man given to appetite. Be not desirous of his dainties: for they are deceitful meat. Labour not to be rich: cease from thine own wisdom. Wilt thou set thine eyes upon that which is not? for riches certainly make themselves wings; they fly away as an eagle toward heaven. Buy the truth, and sell it not; also wisdom, and instruction, and understanding." },
      { id: "prv-kjv-24", reference: "Proverbs 24", title: "Proverbs Chapter 24", text: "Be not thou envious against evil men, neither desire to be with them. For their heart studieth destruction, and their lips talk of mischief. Through wisdom is an house builded; and by understanding it is established: And by knowledge shall the chambers be filled with all precious and pleasant riches. A wise man is strong; yea, a man of knowledge increaseth strength. If thine enemy be hungry, give him bread to eat; and if he be thirsty, give him water to drink: For thou shalt heap coals of fire upon his head, and the LORD shall reward thee." },
      { id: "prv-kjv-25", reference: "Proverbs 25", title: "Proverbs Chapter 25", text: "These are also proverbs of Solomon, which the men of Hezekiah king of Judah copied out. It is the glory of God to conceal a thing: but the honour of kings is to search out a matter. A word fitly spoken is like apples of gold in pictures of silver. As an earring of gold, and an ornament of fine gold, so is a wise reprover upon an obedient ear. Confidence in an unfaithful man in time of trouble is like a broken tooth, and a foot out of joint." },
      { id: "prv-kjv-26", reference: "Proverbs 26", title: "Proverbs Chapter 26", text: "As snow in summer, and as rain in harvest, so honour is not seemly for a fool. As the bird by wandering, as the swallow by flying, so the curse causeless shall not come. The sluggard is wiser in his own conceit than seven men that can render a reason. As a dog returneth to his vomit, so a fool returneth to his folly. Seest thou a man wise in his own conceit? there is more hope of a fool than of him." },
      { id: "prv-kjv-27", reference: "Proverbs 27", title: "Proverbs Chapter 27", text: "Boast not thyself of to morrow; for thou knowest not what a day may bring forth. Let another man praise thee, and not thine own mouth; a stranger, and not thine own lips. Wrath is cruel, and anger is outrageous; but who is able to stand before envy? Faithful are the wounds of a friend; but the kisses of an enemy are deceitful. Iron sharpeneth iron; so a man sharpeneth the countenance of his friend." },
      { id: "prv-kjv-28", reference: "Proverbs 28", title: "Proverbs Chapter 28", text: "The wicked flee when no man pursueth: but the righteous are bold as a lion. He that covereth his sins shall not prosper: but whoso confesseth and forsaketh them shall have mercy. Whoso walketh uprightly shall be saved: but he that is perverse in his ways shall fall at once. He that tilleth his land shall have plenty of bread: but he that followeth after vain persons shall have poverty enough. A faithful man shall abound with blessings: but he that maketh haste to be rich shall not be innocent." },
      { id: "prv-kjv-29", reference: "Proverbs 29", title: "Proverbs Chapter 29", text: "He, that being often reproved hardeneth his neck, shall suddenly be destroyed, and that without remedy. When the righteous are in authority, the people rejoice: but when the wicked beareth rule, the people mourn. Correct thy son, and he shall give thee rest; yea, he shall give delight unto thy soul. Where there is no vision, the people perish: but he that keepeth the law, happy is he. A man's pride shall bring him low: but honour shall uphold the humble in spirit." },
      { id: "prv-kjv-30", reference: "Proverbs 30", title: "Proverbs Chapter 30", text: "The words of Agur the son of Jakeh, even the prophecy: the man spake unto Ithiel, even unto Ithiel and Ucal. Every word of God is pure: he is a shield unto them that put their trust in him. Add thou not unto his words, lest he reprove thee, and thou be found a liar. There be four things which are little upon the earth, but they are exceeding wise: The ants are a people not strong, yet they prepare their meat in the summer; The conies are but a feeble folk, yet make they their houses in the rocks; The locusts have no king, yet go they forth all of them by bands; The spider taketh hold with her hands, and is in kings' palaces." },
    ]
  }
];

// ── Korean ────────────────────────────────────────────────────────────────────
export const VERSE_SETS_PROVERBS_KO = [
  {
    id: "proverbs-ko",
    title: "잠언 1–30",
    description: "잠언 1장부터 30장까지, 한 챕터씩 '경문비'(Rain Mode) 암송 도전.",
    language: "ko",
    verses: [
      { id: "prv-ko-1",  reference: "잠언 1", title: "잠언 1장",  text: "이스라엘 왕 다윗의 아들 솔로몬의 잠언이라 이는 지혜와 훈계를 알게 하며 명철의 말씀을 깨닫게 하며 지혜롭게, 공의롭게, 정의롭게, 정직하게 행할 일에 대하여 훈계를 받게 하며 어리석은 자를 슬기롭게 하며 젊은 자에게 지식과 근신함을 주기 위한 것이니 지혜로운 자는 들어서 학식이 더할 것이요 명철한 자는 모략을 얻을 것이라 여호와를 경외하는 것이 지식의 근본이거늘 미련한 자는 지혜와 훈계를 멸시하느니라 내 아들아 네 아비의 훈계를 들으며 네 어미의 법을 떠나지 말라 이는 네 머리의 아름다운 관이요 네 목의 금 사슬이니라." },
      { id: "prv-ko-2",  reference: "잠언 2", title: "잠언 2장",  text: "내 아들아 네가 만일 나의 말을 받으며 나의 계명을 네게 간직하며 네 귀를 지혜에 기울이며 네 마음을 명철에 두며 지식을 불러 구하며 명철을 얻으려고 소리를 높이며 은을 구하는 것 같이 그것을 구하며 감추어진 보배를 찾는 것 같이 그것을 찾으면 여호와 경외하기를 깨달으며 하나님을 알게 되리니 대저 여호와는 지혜를 주시며 지식과 명철은 그 입에서 나오며 그는 정직한 자를 위하여 완전한 지혜를 예비하시며 행실이 온전한 자에게 방패가 되시나니." },
      { id: "prv-ko-3",  reference: "잠언 3", title: "잠언 3장",  text: "내 아들아 나의 법을 잊어버리지 말고 네 마음으로 나의 명령을 지키라 그리하면 그것이 네가 장수하여 많은 해를 누리게 하며 평강을 더하게 하리라 인자와 진리가 네게서 떠나지 말게 하고 그것을 네 목에 매며 네 마음판에 새기라 그리하면 네가 하나님과 사람 앞에서 은총과 귀중히 여김을 받으리라 너는 마음을 다하여 여호와를 신뢰하고 네 명철을 의지하지 말라 너는 범사에 그를 인정하라 그리하면 네 길을 지도하시리라 네 재물과 네 소산물의 처음 익은 열매로 여호와를 공경하라 그리하면 네 창고가 가득히 차고 네 포도즙 틀에 새 포도즙이 넘치리라." },
      { id: "prv-ko-4",  reference: "잠언 4", title: "잠언 4장",  text: "아들들아 아비의 훈계를 들으며 명철을 얻기에 주의하라 내가 선한 도리를 너희에게 전하노니 내 법을 떠나지 말라 나도 내 아버지에게 아들이었으며 내 어머니 보기에 유약한 외아들이었노라 아버지가 내게 가르쳐 이르기를 내 말을 네 마음에 두라 내 명령을 지키라 그리하면 살리라 지혜를 얻으며 명철을 얻으라 내 입의 말을 잊지 말며 어기지 말라 지혜를 버리지 말라 그가 너를 보호하리라 그를 사랑하라 그가 너를 지키리라 지혜가 제일이니 지혜를 얻으라 주의하여 명철을 얻으라." },
      { id: "prv-ko-5",  reference: "잠언 5", title: "잠언 5장",  text: "내 아들아 내 지혜에 주의하며 내 명철에 네 귀를 기울여서 근신을 지키며 네 입술로 지식을 지키도록 하라 대저 음녀의 입술은 꿀을 떨어뜨리며 그의 입은 기름보다 미끄러우나 나중은 쑥 같이 쓰고 두 날 가진 칼 같이 날카로우며 너는 그 길을 멀리 하라 그의 집 문에도 가까이 가지 말라 젊어서 취한 아내와 함께 즐거워하라 그는 사랑스러운 암사슴 같고 아름다운 암노루 같으니 너는 그의 품을 항상 족하게 여기며 그의 사랑을 항상 연모하라." },
      { id: "prv-ko-6",  reference: "잠언 6", title: "잠언 6장",  text: "내 아들아 네가 만일 이웃을 위하여 담보하며 타인을 위하여 보증하였으면 네 입의 말로 네가 얽혔으며 네 입의 말로 인하여 잡히게 되었느니라 게으른 자여 개미에게 가서 그가 하는 것을 보고 지혜를 얻으라 개미는 두령도 없고 감독자도 없고 통치자도 없으되 먹을 것을 여름 동안에 예비하며 추수 때에 양식을 모으느니라 여호와께서 미워하시는 것 곧 그의 마음에 싫어하시는 것이 육칠 가지이니 곧 교만한 눈과 거짓된 혀와 무죄한 자의 피를 흘리는 손과 악한 계교를 꾀하는 마음과 빨리 악으로 달려가는 발과 거짓을 말하는 망령된 증인과 및 형제 사이를 이간하는 자이니라." },
      { id: "prv-ko-7",  reference: "잠언 7", title: "잠언 7장",  text: "내 아들아 내 말을 지키며 내 명령을 네게 간직하라 내 명령을 지켜 살며 내 법을 네 눈동자처럼 지키라 이것을 네 손가락에 매며 이것을 네 마음판에 새기라 지혜에게 너는 내 누이라 하며 명철에게 너는 내 친족이라 하라 그리하면 그것이 너를 음녀에게서, 말로 호리는 이방 여인에게서 지키리라 내가 어리석은 자 중에, 젊은이들 가운데에서 한 지혜 없는 자를 보았노라 이 젊은이가 그녀의 집 쪽으로 그 길로 지나 그녀의 모퉁이에서 걸어가다가." },
      { id: "prv-ko-8",  reference: "잠언 8", title: "잠언 8장",  text: "지혜가 부르지 아니하느냐 명철이 소리를 높이지 아니하느냐 길가의 높은 곳과 네 거리가 만나는 곳에 서며 성문 곁과 문 어귀와 여러 출입하는 문에서 불러 이르되 너희에게 부르짖나니 여호와께서 그 조화의 시작 곧 태초에 일하시기 전에 나를 가지셨으며 만세 전부터, 태초부터, 땅이 생기기 전부터 내가 세움을 받았나니 그 때에 나는 그 곁에 있어서 창조자가 되어 날마다 그의 기뻐하신 바가 되었으며 항상 그 앞에서 즐거워하였으며 사람이 거처할 땅에서 즐거워하며 인자들을 기뻐하였느니라." },
      { id: "prv-ko-9",  reference: "잠언 9", title: "잠언 9장",  text: "지혜가 그의 집을 짓고 일곱 기둥을 다듬고 짐승을 잡으며 포도주를 혼합하여 상을 갖추고 사람을 보내어 성중 높은 곳에서 불러 이르되 어리석은 자는 이리로 돌이키라 또 지혜 없는 자에게 이르기를 너는 와서 내 식물을 먹으며 내 혼합한 포도주를 마시고 어리석음을 버리고 살며 명철의 길을 행하라 거만한 자를 징계하는 자는 도리어 능욕을 받고 악인을 책망하는 자는 도리어 흠을 잡히느니라 지혜로운 자를 책망하라 그가 너를 사랑하리라 지혜로운 자에게 교훈을 더하라 그가 더욱 지혜로워질 것이요 의로운 사람을 가르치라 그의 학식이 더하리라 여호와를 경외하는 것이 지혜의 근본이요 거룩하신 자를 아는 것이 명철이니라." },
      { id: "prv-ko-10", reference: "잠언 10", title: "잠언 10장", text: "지혜로운 아들은 아비를 기쁘게 하거니와 미련한 아들은 어미의 근심이니라 불의의 재물은 무익하여도 공의는 죽음에서 건지느니라 여호와께서 의인의 영혼은 주리지 않게 하시나 악인의 소욕은 물리치시느니라 손을 게으르게 놀리는 자는 가난하게 되고 손이 부지런한 자는 부하게 되느니라 여름에 거두는 자는 슬기로운 아들이나 추수 때에 자는 자는 부끄러움을 끼치는 아들이니라 의인을 기념할 때에는 칭찬하거니와 악인의 이름은 썩으리라." },
      { id: "prv-ko-11", reference: "잠언 11", title: "잠언 11장", text: "속이는 저울은 여호와께서 미워하시나 공평한 추는 그가 기뻐하시느니라 교만이 오면 욕도 오거니와 겸손한 자에게는 지혜가 있느니라 정직한 자의 성실은 자기를 인도하거니와 사악한 자의 패역은 자기를 망하게 하느니라 흩어 구제하여도 더욱 부하게 되는 일이 있나니 과도히 아껴도 가난하게 될 뿐이니라 구제를 좋아하는 자는 풍족하여질 것이요 남을 윤택하게 하는 자는 자기도 윤택하여지리라 곡식을 내지 아니하는 자는 백성에게 저주를 받을 것이나 파는 자는 그의 머리에 복이 임하리라." },
      { id: "prv-ko-12", reference: "잠언 12", title: "잠언 12장", text: "훈계를 좋아하는 자는 지식을 좋아하거니와 징계를 싫어하는 자는 짐승과 같으니라 선인은 여호와께 은총을 받거니와 악을 꾀하는 자는 정죄를 받으리라 어진 여인은 그 지아비의 면류관이나 욕을 끼치는 여인은 그 지아비의 뼈가 썩음 같게 하느니라 의인의 생각은 공직하거니와 악인의 도모는 속임이니라 악인의 말은 사람을 엿보아 피를 흘리자 하는 것이거니와 정직한 자의 입은 사람을 구원하느니라 부지런한 자의 손은 다스리게 되어도 게으른 자는 부림을 받느니라." },
      { id: "prv-ko-13", reference: "잠언 13", title: "잠언 13장", text: "지혜로운 아들은 아비의 훈계를 들으나 거만한 자는 꾸지람을 듣지 아니하느니라 사람은 입의 열매로 말미암아 복록을 누리거니와 마음이 패역한 자는 강포를 당하느니라 입을 지키는 자는 자기의 생명을 보전하나 입술을 크게 벌리는 자에게는 멸망이 오느니라 게으른 자는 마음으로 원하여도 얻지 못하나 부지런한 자의 마음은 풍족함을 얻느니라 바라는 것이 더디 이루어지면 그것이 마음을 상하게 하거니와 소원이 이루어지는 것은 곧 생명 나무니라." },
      { id: "prv-ko-14", reference: "잠언 14", title: "잠언 14장", text: "지혜로운 여인은 자기 집을 세우되 미련한 여인은 자기 손으로 그것을 허느니라 정직하게 행하는 자는 여호와를 경외하여도 패역하게 행하는 자는 여호와를 경멸하느니라 미련한 자는 교만하여 입으로 매를 자청하고 지혜로운 자의 입술은 자기를 보전하느니라 여호와를 경외하는 것은 생명의 샘이니 사망의 그물에서 벗어나게 하느니라 백성이 많은 것이 왕의 영광이요 백성이 적은 것은 주권자의 패망이니라 노하기를 더디 하는 자는 크게 명철하여도 마음이 조급한 자는 어리석음을 나타내느니라." },
      { id: "prv-ko-15", reference: "잠언 15", title: "잠언 15장", text: "유순한 대답은 분노를 쉬게 하여도 과격한 말은 노를 격동하느니라 지혜 있는 자의 혀는 지식을 선히 베풀고 미련한 자의 입은 미련한 것을 쏟느니라 여호와의 눈은 어디서든지 악인과 선인을 감찰하시느니라 온순한 혀는 곧 생명 나무이지만 패역한 혀는 마음을 상하게 하느니라 여호와를 경외하는 것은 지혜의 훈계라 겸손은 존귀의 길잡이니라 가산이 적어도 여호와를 경외하는 것이 크게 부하고 번뇌하는 것보다 나으니라." },
      { id: "prv-ko-16", reference: "잠언 16", title: "잠언 16장", text: "마음의 경영은 사람에게 있어도 말의 응답은 여호와께로부터 나오느니라 사람의 행위가 자기 보기에는 모두 깨끗하여도 여호와는 심령을 감찰하시느니라 너의 행사를 여호와께 맡기라 그리하면 네가 경영하는 것이 이루어지리라 교만은 패망의 선봉이요 거만한 마음은 넘어짐의 앞잡이니라 겸손하고 가난한 자와 함께 있는 것이 교만한 자와 함께 하여 탈취물을 나누는 것보다 나으니라." },
      { id: "prv-ko-17", reference: "잠언 17", title: "잠언 17장", text: "마른 떡 한 조각만 있고도 화목하는 것이 제육이 집에 가득하고 다투는 것보다 나으니라 슬기로운 종은 부끄러운 아들을 다스리겠고 또 형제들 중에서 유업을 나누어 받으리라 도가니는 은을, 풀무는 금을 연단하거니와 여호와는 마음을 연단하시느니라 친구는 사랑이 끊이지 아니하고 형제는 위급한 때를 위하여 났느니라 마음의 즐거움은 양약이라도 심령의 근심은 뼈를 마르게 하느니라 미련한 자라도 잠잠하면 지혜로운 자로 여겨지고 그의 입술을 닫으면 슬기로운 자로 여겨지느니라." },
      { id: "prv-ko-18", reference: "잠언 18", title: "잠언 18장", text: "무리에게서 스스로 나뉘는 자는 자기 소욕을 따르는 자라 온갖 참 지혜를 배척하느니라 미련한 자는 명철을 기뻐하지 아니하고 자기의 의사를 드러내기만 기뻐하느니라 사람의 입에서 나오는 말은 깊은 물과 같고 지혜의 샘은 솟구쳐 흐르는 내와 같으니라 여호와의 이름은 견고한 망대라 의인은 그리로 달려가서 안전함을 얻느니라 죽고 사는 것이 혀의 힘에 달렸나니 혀를 쓰기 좋아하는 자는 혀의 열매를 먹으리라." },
      { id: "prv-ko-19", reference: "잠언 19", title: "잠언 19장", text: "가난하여도 성실하게 행하는 자는 입술이 패역하고 미련한 자보다 나으니라 지식 없는 소욕은 선하지 못하고 발이 급한 사람은 잘못 가느니라 재물은 친구를 많이 두지만 가난한 자는 그 이웃에게서 끊어지느니라 거짓 증인은 벌을 면하지 못할 것이요 거짓말을 내뱉는 자도 피하지 못하리라 집과 재물은 조상에게서 상속하거니와 슬기로운 아내는 여호와께로서 말미암느니라 가난한 자를 불쌍히 여기는 것은 여호와께 꾸어 드리는 것이니 그의 선행을 그에게 갚아 주시리라 네 아들을 징계하라 그리하면 그가 너를 평안하게 하겠고 또 네 마음에 기쁨을 주리라." },
      { id: "prv-ko-20", reference: "잠언 20", title: "잠언 20장", text: "포도주는 거만하게 하는 것이요 독주는 떠들게 하는 것이라 이에 미혹되는 자마다 지혜롭지 못하니라 왕의 진노는 사자의 부르짖음 같으니 그를 노하게 하는 것은 자기의 생명을 해하는 것이니라 게으른 자는 가을에 밭 갈지 아니하나니 그러므로 거둘 때에는 구걸할지라도 얻지 못하리라 사람의 마음에 있는 모략은 깊은 물 같으니라 그럴지라도 명철한 사람은 그것을 길어 내느니라 많은 사람이 각기 자기의 인자함을 자랑하나니 충성된 자를 누가 만날 수 있으랴." },
      { id: "prv-ko-21", reference: "잠언 21", title: "잠언 21장", text: "왕의 마음이 여호와의 손에 있음이 마치 봇물과 같아서 그가 임의로 인도하시느니라 사람의 행위가 자기 보기에는 모두 정직하여도 여호와는 마음을 감찰하시느니라 공의와 정의를 행하는 것은 제사 드리는 것보다 여호와께서 기쁘게 여기시느니라 게으른 자의 소욕이 그를 죽이나니 이는 그의 손이 일하기를 거절하기 때문이라 부지런한 자의 손은 다스리게 되어도 게으른 자는 부림을 받느니라." },
      { id: "prv-ko-22", reference: "잠언 22", title: "잠언 22장", text: "많은 재물보다 명예를 택할 것이요 은이나 금보다 은총을 더욱 택할 것이니라 부자와 가난한 자가 함께 살거니와 그 모두를 지으신 이는 여호와시니라 슬기로운 자는 재앙을 보면 숨어 피하여도 어리석은 자는 나가다가 해를 받느니라 겸손과 여호와를 경외함의 보상은 재물과 영광과 생명이니라 마땅히 행할 길을 아이에게 가르치라 그리하면 늙어도 그것을 떠나지 아니하리라." },
      { id: "prv-ko-23", reference: "잠언 23", title: "잠언 23장", text: "네가 관원과 함께 앉아 음식을 먹게 되거든 삼가 네 앞에 있는 자가 누구인지를 생각하며 네가 만일 탐욕스러운 자이거든 네 목에 칼을 댈지니라 그 진수성찬을 탐내지 말라 그것은 간사한 음식이니라 부자 되기에 애쓰지 말고 네 사사로운 지혜를 버릴지어다 재물은 새가 되어 하늘을 나는 독수리처럼 날아가버리므로 네 눈을 재물에 두고 있지 말지어다 진리를 사고 팔지 말며 지혜와 훈계와 명철도 그리할지니라." },
      { id: "prv-ko-24", reference: "잠언 24", title: "잠언 24장", text: "너는 악인의 형통함을 부러워하지 말며 그와 함께 있으려고 하지도 말지어다 그들의 마음은 강포를 품고 그들의 입술은 재앙을 말함이니라 집은 지혜로 말미암아 건축되고 명철로 말미암아 견고하게 되며 또 방들은 지식으로 말미암아 각종 귀하고 아름다운 보배로 채우게 되느니라 지혜 있는 자는 강하고 지식 있는 자는 힘을 더하나니 네 원수가 주리거든 음식을 먹이고 목마르거든 물을 마시게 하라 그리하는 것은 숯불을 그의 머리에 쌓아 놓는 것과 일반이요 여호와께서 네게 상 주시리라." },
      { id: "prv-ko-25", reference: "잠언 25", title: "잠언 25장", text: "이것도 솔로몬의 잠언이요 유다 왕 히스기야의 신하들이 편집한 것이니라 일을 숨기는 것은 하나님의 영화요 일을 살피는 것은 왕의 영화니라 경우에 합당한 말은 아로새긴 은 쟁반에 금 사과니라 슬기로운 자의 책망은 청종하는 귀에 금 고리와 정금 장식이니라." },
      { id: "prv-ko-26", reference: "잠언 26", title: "잠언 26장", text: "여름에 눈 오는 것과 추수 때에 비 오는 것 같이 미련한 자에게 존귀를 주는 것도 마땅하지 아니하니라 까닭 없는 저주는 참새가 떠도는 것과 제비가 날아가는 것 같이 이루어지지 아니하느니라 게으른 자는 자기를 복종시키겠다는 자보다 자기를 더 지혜롭다 여기느니라 개가 그 토한 것을 도로 먹는 것 같이 미련한 자는 그 미련한 것을 거듭 행하느니라 스스로 지혜롭다 여기는 사람을 보느냐 그보다 미련한 자에게 오히려 희망이 있느니라." },
      { id: "prv-ko-27", reference: "잠언 27", title: "잠언 27장", text: "내일 일을 자랑하지 말라 하루 동안에 무슨 일이 일어날는지 네가 알 수 없음이니라 타인이 너를 칭찬하게 하고 네 입으로는 하지 말며 외인이 너를 칭찬하게 하고 네 입술로는 하지 말지니라 돌은 무겁고 모래도 가볍지 아니하거니와 미련한 자의 분노는 이 둘보다 더 무거우니라 잔혹한 분노와 넘치는 노여움 앞에서야 누가 능히 서리요마는 투기 앞에서랴 친구의 통책은 충성스러운 것이지만 원수의 입맞춤은 피차 어울리지 아니하느니라 쇠가 쇠를 날카롭게 하는 것 같이 사람이 그의 친구의 얼굴을 빛나게 하느니라." },
      { id: "prv-ko-28", reference: "잠언 28", title: "잠언 28장", text: "악인은 쫓아오는 자가 없어도 도망하나 의인은 사자 같이 담대하니라 자기의 죄를 숨기는 자는 형통하지 못하나 죄를 자복하고 버리는 자는 불쌍히 여김을 받으리라 성실하게 행하는 자는 구원을 받을 것이나 굽은 길로 행하는 자는 곧 넘어지리라 자기의 토지를 경작하는 자는 먹을 것이 많으려니와 방탕을 따르는 자는 궁핍함이 많으리라 충성된 자는 복이 많아도 속히 부하고자 하는 자는 형벌을 면하지 못하리라." },
      { id: "prv-ko-29", reference: "잠언 29", title: "잠언 29장", text: "자주 책망을 받으면서도 목이 굳은 사람은 갑자기 패망을 당하고 치유 받지 못하리라 의인이 많으면 백성이 즐거워하고 악인이 권세를 잡으면 백성이 탄식하느니라 네 아들을 징계하라 그리하면 그가 너를 평안하게 하겠고 또 네 마음에 기쁨을 주리라 묵시가 없으면 백성이 방자히 행하거니와 율법을 지키는 자는 복이 있느니라 사람의 교만은 그를 낮추나 마음이 낮은 자는 영예를 얻느니라." },
      { id: "prv-ko-30", reference: "잠언 30", title: "잠언 30장", text: "야게의 아들 아굴의 잠언 곧 그가 이디엘 곧 이디엘과 우갈에게 이른 말이라 나는 다른 사람에게 비하면 짐승이라 내게는 사람의 총명이 있지 아니하니라 나는 지혜를 배우지 못하였고 또 거룩하신 자를 아는 지식이 없거니와 하나님의 말씀은 다 순전하며 하나님은 그를 의지하는 자의 방패시니라 너는 그의 말씀에 더하지 말라 그가 너를 책망하시겠고 너는 거짓말하는 자가 될까 두려우니라 땅에 작고도 가장 지혜로운 것 넷이 있나니 곧 힘이 없는 종류이로되 먹을 것을 여름 동안에 준비하는 개미와 약한 종류이로되 집을 바위 사이에 짓는 사반과 임금이 없으되 다 떼를 지어 나아가는 메뚜기와 손에 잡힐 만하여도 왕궁에 있는 도마뱀이니라." },
    ]
  }
];

// ── Japanese ──────────────────────────────────────────────────────────────────
export const VERSE_SETS_PROVERBS_JA = [
  {
    id: "proverbs-ja",
    title: "箴言 1–30（日本語）",
    description: "箴言1章から30章まで、1章ずつ「御言葉の雨」モードで暗唱にチャレンジ。",
    language: "ja",
    verses: [
      { id: "prv-ja-1",  reference: "箴言 1",  title: "箴言第1章",  text: "これはイスラエルの王、ダビデの子ソロモンの箴言である。知恵と訓戒を知り、悟りの言葉を理解し、公義と公正と正直について、訓戒の言葉を受け入れるためのもの。思慮のない者に分別を与え、若者に知識と思慮分別を与えるためのもの。知恵のある者は聞いてさらに知識を増し、理解のある者は導きを得る。主を恐れることは知識の初めである。愚かな者は知恵と訓戒を軽蔑する。息子よ、父の訓戒に聞き従え。母の教えを捨ててはならない。それらは、あなたの頭への麗しい飾りの冠、あなたの首へのネックレスとなる。" },
      { id: "prv-ja-2",  reference: "箴言 2",  title: "箴言第2章",  text: "息子よ、もしあなたが私のことばを受け入れ、私の命令をあなたのうちに蓄え、知恵に耳を傾け、英知に心を向け、悟りを求めて声をあげ、理解を求めて声を張り上げ、銀を求めるように、それを求め、隠れた宝を探し求めるなら、あなたは主を恐れることを理解し、神の知識を見出すことができる。主は知恵を与えてくださるからだ。御口から、知識と英知が出る。主は直ぐな者のために完全な知恵をたくわえ、完全に歩む者に盾となってくださる。" },
      { id: "prv-ja-3",  reference: "箴言 3",  title: "箴言第3章",  text: "息子よ、私の教えを忘れるな。私の命令を心に留めよ。それがあなたに長いよわいと、いのちの年とを多く与え、平和を加えるから。慈しみとまことをあなたから離れさせるな。それをあなたの首に結び、あなたの心の板に書き記せ。そうすれば、あなたは神と人の目に恵みと良識を見出す。心を尽くして主に信頼し、自分の理解に頼るな。あなたのすべての道で主を認めよ。そうすれば、主はあなたの道をまっすぐにされる。あなたの財産と、あなたのすべての収穫の初物で主を敬え。そうすれば、あなたの倉は食物で満たされ、あなたの酒ぶねは新しいぶどう酒で溢れる。" },
      { id: "prv-ja-4",  reference: "箴言 4",  title: "箴言第4章",  text: "息子たちよ、父の訓戒を聞き、英知を得ることに心を留めよ。私はあなたがたに良い教えを授ける。私の指導を捨てるな。私も私の父にとっての息子、母にとって愛されていた一人っ子であった。父は私に教えて言った。「私のことばを心に留め、私の命令を守れ。そうすれば生きる。知恵を得よ、英知を得よ。忘れるな、私の口のことばから離れるな。知恵を捨てるな。彼女があなたを守る。彼女を愛せよ、彼女があなたを保護する。知恵が最も大切なものだ。だから知恵を得よ。あなたの何を得るにしても、英知を得よ。」" },
      { id: "prv-ja-5",  reference: "箴言 5",  title: "箴言第5章",  text: "息子よ、私の知恵に注意を払い、私の英知に耳を傾けよ。分別を保ち、あなたの唇が知識を守るように。見知らぬ女の唇は蜂蜜を滴らせ、その口は油よりも滑らかだ。だが結局は苦よもぎのように苦く、両刃の剣のように鋭い。彼女から遠ざかれ、彼女の家の戸口に近づくな。若い時に娶った妻と共に喜べ。引き寄せられる牝鹿、麗しい野生の羝のように、彼女の乳房がいつもあなたを満足させ、彼女への愛があなたを常に魅了するようにせよ。" },
      { id: "prv-ja-6",  reference: "箴言 6",  title: "箴言第6章",  text: "息子よ、もしあなたが隣人の保証人になり、他人のために握手したなら、あなたは自分の言ったことばに縛られ、自分の口のことばによって捕えられている。怠け者よ、蟻のところへ行き、その生き方を見て知恵を得よ。蟻には長もなく、監督者もなく、支配者もいないのに、夏のうちに食物を備え、刈り入れのときに食料を集める。主が憎むことが六つある。いや、七つのことがご自身への忌まわしいもの。高慢な目、偽りの舌、罪のない者の血を流す手、邪悪な計略を巡らす心、悪に走るのに速い足、偽証する嘘の証人、兄弟の間に争いを起こす者。" },
      { id: "prv-ja-7",  reference: "箴言 7",  title: "箴言第7章",  text: "息子よ、私のことばを守り、私の命令をあなたのうちに蓄えよ。私の命令を守れ、そうすれば生きる。私の教えを目の瞳のように守れ。それをあなたの指に結び、あなたの心の板に書き記せ。知恵に言え、「あなたは私の姉妹だ」と。英知を親族と呼べ。そうすれば、それがあなたを他国の女から、滑らかなことばで誘う女から守ってくれる。私は自分の家の窓から、格子越しに見下ろした。思慮のない者たちの中に、若者の中に、分別のない青年を見た。" },
      { id: "prv-ja-8",  reference: "箴言 8",  title: "箴言第8章",  text: "知恵は呼ばわらないか。英知は声を張り上げないか。彼女は道端の高いところに、十字路のかたわらに立ち、門のかたわら、都の入口で、出入り口で叫んでいる。主は、その働きの初めに、いにしえのみわざの最初として、私を造られた。永遠の昔から、初めから、大地が造られる前から、私は立てられた。私はその傍らで、職人のように御そばにいた。日ごとに主の喜びとなり、いつも主の前で喜び楽しみ、御作りになった地の上で喜び、人の子らとともに楽しんでいた。" },
      { id: "prv-ja-9",  reference: "箴言 9",  title: "箴言第9章",  text: "知恵はその家を建て、七本の柱を刻んだ。家畜を屠り、ぶどう酒を混ぜ合わせ、食卓を整えた。愚かな者が回れ右をして入って来るように、思慮のない者に、「来なさい、私のパンを食べ、私の混ぜ合わせたぶどう酒を飲みなさい。愚かさを捨てて生きなさい。英知の道を歩みなさい」と言った。あざける者を懲らしめると、かえって恥辱を受ける。悪者を戒めると、かえってそしりを受ける。あざける者を戒めるな。彼があなたを憎む。知恵のある者を戒めよ。彼はあなたを愛する。主を恐れることは知恵の初めであり、聖なる方を知ることは英知である。" },
      { id: "prv-ja-10", reference: "箴言 10", title: "箴言第10章", text: "知恵のある息子は父を喜ばせ、愚かな息子は母の悲しみとなる。不正なことで得た財宝は益にならないが、義は死から救い出す。主は義人の魂を飢えさせないが、悪者の欲望を退ける。怠慢な手は貧しさをもたらすが、勤勉な手は富をもたらす。夏のうちに刈り集める者は、思慮深い息子だが、刈り入れ時に眠る者は、恥を招く息子だ。義人の記念は祝福であるが、悪者の名は腐る。" },
      { id: "prv-ja-11", reference: "箴言 11", title: "箴言第11章", text: "いかさまのはかりは主への忌まわしいものだが、正確なおもりは主のお喜びになるものだ。高慢が来ると、恥も来る。謙遜な者には知恵がある。直ぐな者の誠実は彼らを導く。だが不正を行う者の曲がった心は、彼らを滅ぼす。自分のものをばら撒いているのに、さらに豊かになる人がいる。過度に惜しんでいるのに、貧乏になるだけの人がいる。気前のよい人は豊かにされ、潤す人は自分も潤される。穀物をため込む者は民に呪われるが、穀物を売る者の頭には祝福が来る。" },
      { id: "prv-ja-12", reference: "箴言 12", title: "箴言第12章", text: "訓練を愛する者は知識を愛し、叱責を嫌う者は愚かな者だ。善人は主から恵みを受けるが、悪い計画を立てる者は主に正罪される。有能な妻は夫の冠だが、恥をかかせる妻は夫の骨の腐りのようだ。義人の考えは正しいが、悪者の計画は偽りだ。悪者のことばは血を流す伏兵だが、直ぐな者の口は人を救う。勤勉な者の手は支配するようになるが、怠け者は強制労働につかされる。" },
      { id: "prv-ja-13", reference: "箴言 13", title: "箴言第13章", text: "知恵のある息子は父の訓戒を聞くが、あざける者は叱責に耳を貸さない。人は口の実によって良いものを食べ、裏切る者の魂は強暴をむさぼる。口を守る者は自分のいのちを守るが、唇を大きく開く者には破滅が来る。怠け者の魂は切望するが、何も得ない。勤勉な者の魂は豊かに与えられる。望みが長引くと、心が病む。しかし、欲求が満たされると、それはいのちの木となる。" },
      { id: "prv-ja-14", reference: "箴言 14", title: "箴言第14章", text: "知恵のある女は自分の家を建て、愚かな女は自分の手でそれを壊す。誠実に歩む者は主を恐れるが、道が曲がっている者は主を侮る。愚か者の口は高慢な杖だが、知恵のある者の唇は彼らを守る。主を恐れることはいのちの泉であり、死の網から救い出す。民が多いことは王の栄光だが、民が少ないことは君主の破滅だ。怒るのが遅い人は、大いなる英知を持ち、短気な人は愚かさを高める。" },
      { id: "prv-ja-15", reference: "箴言 15", title: "箴言第15章", text: "やさしい答えは怒りを退け、傷つけることばは怒りを引き起こす。知恵のある者の舌は知識を正しく用いるが、愚か者の口は愚かさを吐き出す。主の目はあらゆるところにあり、悪人も善人も見守っている。健やかな舌はいのちの木だが、曲がった舌は霊を傷つける。財産が少なくても主を恐れる方が、財産が多くて混乱するよりよい。主を恐れることは知恵の訓練であり、謙遜は栄誉に先立つ。" },
      { id: "prv-ja-16", reference: "箴言 16", title: "箴言第16章", text: "心の計画は人に属するが、舌の答えは主から来る。人のすべての道は自分の目には清らかだが、主は霊を計られる。あなたのわざを主に委ねよ。そうすれば、あなたの計画はゆるぎないものとなる。高慢は破滅に先立ち、高ぶった心はつまずきに先立つ。謙遜な者と共に、低い者とともにいる方が、高慢な者と共にいて、戦利品を分かち合うよりよい。人の心はその道を計画するが、主がその歩みを確かにされる。" },
      { id: "prv-ja-17", reference: "箴言 17", title: "箴言第17章", text: "いけにえが家に満ちていて争いがあるよりも、乾いたパン一切れで平和な方がよい。練り鍋は銀のためにあり、炉は金のためにある。しかし、主は心を練られる。友はどんなときにも愛し、兄弟は苦難のときのために生まれる。喜んでいる心は良い薬だが、打ち砕かれた霊は骨を乾かす。たとえ愚かな者でも、黙っていれば知恵があると思われ、唇を閉じていれば思慮深いと思われる。" },
      { id: "prv-ja-18", reference: "箴言 18", title: "箴言第18章", text: "自分を他から切り離す者は、自分の欲求を追い求め、すべての確かな知恵を拒む。愚かな者は理解することを喜ばず、自分の考えを披露することを喜ぶ。人の言葉は深い水のよう。知恵の泉はあふれ出る流れ川のよう。主の御名は堅固なやぐらだ。義人はそこに走り込んで安全を得る。死と生は舌の力にある。舌を愛する者はその実を食べる。" },
      { id: "prv-ja-19", reference: "箴言 19", title: "箴言第19章", text: "貧しくても誠実に歩む者は、唇が曲がっていて愚かな者よりよい。知識のない熱心さはよくなく、急ぎすぎる足は道を踏み外す。財産は多くの友を作るが、貧しい者は友から離れる。偽りの証人は罰を免れず、嘘をつく者は滅びる。家と財産は先祖から受け継ぐが、思慮深い妻は主からのものだ。貧しい者を憐れむ者は主に貸しており、主はその善行を報いてくださる。あなたの息子を訓練せよ。そうすれば、彼はあなたに安らぎを与え、魂に喜びをもたらす。" },
      { id: "prv-ja-20", reference: "箴言 20", title: "箴言第20章", text: "ぶどう酒は人をあざける者。強い酒は騒ぐ者だ。どんな人もそれによって惑わされるなら、知恵がない。王の怒りはライオンの唸り声のようだ。彼を怒らせる者は自分の魂に罪を犯す。怠け者は寒さゆえに耕さない。それで刈り入れ時になっても、何も得られない。人の心の中の計画は深い水のようだ。しかし、思慮深い人はそれを汲み出すことができる。多くの人は自分の親切について語るが、誰が信頼できる人を見つけられるか。" },
      { id: "prv-ja-21", reference: "箴言 21", title: "箴言第21章", text: "王の心は主の手の中にある。水路のように、主はそれを御心の向くままに向けられる。人の道はすべて、自分の目には正しい。しかし、主は霊を計られる。公義と公正を行うことは、いけにえをささげるよりも主に喜ばれる。怠け者の欲求は彼を殺す。彼の手は働くことを拒むから。勤勉な者の手は支配するようになるが、怠け者は強制労働につかされる。" },
      { id: "prv-ja-22", reference: "箴言 22", title: "箴言第22章", text: "多くの富よりも、良い名声の方を選べ。銀や金よりも、恵みを選べ。富む者と貧しい者は共に生きる。彼ら全員を造られたのは主だ。思慮深い者は災いを見て身を隠すが、愚かな者は進んでいって罰を受ける。謙遜と主への恐れの報いは、富と名誉といのちだ。子どもを行くべき道にふさわしく訓練せよ。そうすれば、老いてもそれから離れない。" },
      { id: "prv-ja-23", reference: "箴言 23", title: "箴言第23章", text: "あなたが支配者と共に食事のために座るときは、自分の前にいるのが誰なのかをよく考えよ。もしあなたが食欲旺盛なら、自分ののどにナイフを当てよ。彼のご馳走を求めるな。それは人を欺く食べ物だ。富もうと労苦するな、自分の知恵はやめよ。財産に目を向けるな、それが翼をつけて、鷲のように空に飛んでいくから。真理を買え、売り渡すな。知恵と訓練と英知もそうせよ。" },
      { id: "prv-ja-24", reference: "箴言 24", title: "箴言第24章", text: "悪者たちをうらやむな、彼らと一緒にいたいと思うな。彼らの心は暴力を研究しており、彼らの唇は害悪を語るから。知恵によって家は建てられ、英知によって確立される。また、部屋は知識によって、あらゆる貴重で美しい財宝で満たされる。知恵のある者は強い。知識のある人は力を増す。もしあなたの敵が飢えているなら、彼にパンを与えて食べさせよ。渇いているなら、水を与えて飲ませよ。そうすれば、あなたは彼の頭に炭火を積むことになり、主はあなたに報いてくださる。" },
      { id: "prv-ja-25", reference: "箴言 25", title: "箴言第25章", text: "これもソロモンの箴言であり、ユダの王ヒゼキヤの人々が書き写したものだ。事を隠すことは神の栄光であり、事を調べることは王の栄光だ。時宜にかなったことばは、銀の器に盛った金のリンゴのようだ。聞く耳に対する知恵ある者の叱責は、金の指輪、上質な金の飾りのようだ。" },
      { id: "prv-ja-26", reference: "箴言 26", title: "箴言第26章", text: "夏の雪のように、刈り入れ時の雨のように、愚か者への栄誉もふさわしくない。あてもなくさまよう雀のように、飛び回るつばめのように、理由のない呪いはやって来ない。怠け者は七人の相談相手を持つよりも、自分を賢いと思っている。犬が自分の吐いたものに戻るように、愚か者はその愚かさを繰り返す。自分が賢いと思っている人を見るか。愚か者でも、その人よりもましだ。" },
      { id: "prv-ja-27", reference: "箴言 27", title: "箴言第27章", text: "明日のことを誇るな。一日のうちに何が起こるか、あなたは知らないから。他の者があなたを褒めるようにせよ、あなた自身の口でなく。見知らぬ者があなたを褒めるようにせよ、あなた自身の唇でなく。石は重く、砂は重い。しかし、愚か者の怒りは、その両方よりも重い。残酷な怒り、溢れる激怒—誰がそれに立ち向かえるか。妬みにはなおさら。友の傷は誠実なものだが、敵のキスは欺きだ。鉄が鉄を研ぐように、人は友人の顔を研ぐ。" },
      { id: "prv-ja-28", reference: "箴言 28", title: "箴言第28章", text: "悪者は誰も追いかけていないのに逃げる。しかし、義人はライオンのように大胆だ。自分の罪を隠す者は栄えないが、罪を告白して捨てる者はあわれみを受ける。誠実に歩む者は救われるが、曲がった道を歩む者はすぐに倒れる。自分の土地を耕す者は食べ物に満ち足りるが、空しいことを追う者は貧困に陥る。忠実な者は多くの祝福を受けるが、急いで富もうとする者は罰を免れない。" },
      { id: "prv-ja-29", reference: "箴言 29", title: "箴言第29章", text: "しばしば戒められながらも、うなじを固くする者は、突然打ち砕かれ、癒やしもなく破壊される。義人が多くなると、民は喜ぶ。しかし、悪者が支配すると、民はうめく。あなたの息子を訓練せよ。そうすれば、彼はあなたに安らぎを与え、あなたの魂に喜びをもたらす。幻がなければ、民は放縦になる。しかし、律法を守る者は幸いだ。人の高慢は彼を低くする。しかし、霊の謙遜な者は栄誉を保つ。" },
      { id: "prv-ja-30", reference: "箴言 30", title: "箴言第30章", text: "ヤケの子アグルのことば、神託。この人はイティエルに、イティエルとウカルに語った。私は他の人よりも愚かで、人間の理解力がない。私は知恵を学ばず、聖なる方の知識を持っていない。神のみことばはすべて清らかだ。神は御自身に拠り頼む者の盾だ。御言葉に加えるな。そうでなければ、神があなたを責め、あなたは嘘つきになってしまう。地に小さくて、それでも非常に知恵のあるものが四つある。蟻は力のない生き物だが、夏のうちに食料を準備する。岩だぬきは弱い生き物だが、岩の中に家を作る。いなごは王がいないが、みな隊を組んで出て行く。" },
    ]
  }
];
